### ISSUE TITLE
微调报错dataclasses.FrozenInstanceError

### ISSUE THREAD

**Issue by SilenceWinter** [FlagOpen/FlagEmbedding#107]
ubuntu20.04， python=3.9.16， FlagEmbedding=1.1.0，
**运行：**
torchrun --nproc_per_node 1 \
-m FlagEmbedding.baai_general_embedding.finetune.run \
--output_dir . \
--model_name_or_path /home/xxxxx/textvec/bge-base-en \
--train_data /home/xxxxx/pyproj/FlagEmbedding/toy_finetune_data.jsonl \
--learning_rate 1e-5 \
--fp16 \
--num_train_epochs 5 \
--per_device_train_batch_size 1 \
--dataloader_drop_last True \
--normlized True \
--temperature 0.02 \
--query_max_len 64 \
--passage_max_len 256 \
--train_group_size 2 \
--negatives_cross_device \
--query_instruction_for_retrieval "为这个句子生成表示以用于检索相关文章："

**报错信息：**  

Traceback (most recent call last):
  File "/home/xxxxx/miniconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxxxx/miniconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxxxx/miniconda3/envs/py39/lib/python3.9/site-packages/FlagEmbedding/baai_general_embedding/finetune/run.py", line 110, in <module>
    main()
  File "/home/xxxxx/miniconda3/envs/py39/lib/python3.9/site-packages/FlagEmbedding/baai_general_embedding/finetune/run.py", line 76, in main
    training_args.sentence_pooling_method = model_args.sentence_pooling_method
  File "/home/xxxxx/miniconda3/envs/py39/lib/python3.9/site-packages/transformers/training_args.py", line 1712, in __setattr__
    raise FrozenInstanceError(f"cannot assign to field {name}")
dataclasses.FrozenInstanceError: cannot assign to field sentence_pooling_method
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1010846) of binary: /home/xxxxx/miniconda3/envs/py39/bin/python
Traceback (most recent call last):
  File "/home/xxxxx/miniconda3/envs/py39/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/xxxxx/miniconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/xxxxx/miniconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/xxxxx/miniconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/xxxxx/miniconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xxxxx/miniconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

FlagEmbedding.baai_general_embedding.finetune.run FAILED

**Comment by staoxiao** [comment]
原有代码在某些环境下确实会有问题。我们修改了一下代码，您可以git clone最新版的FlagEmbedding，重新安装，应该可以解决这个问题。
