### ISSUE TITLE
Found and fixed a BUG when not using knowledge_distilation in fine-tuning.

### ISSUE THREAD

**Issue by yjoonjang** [FlagOpen/FlagEmbedding#1170]
Hello, @545999961.
I was fine-tuning bge-m3, and found a bug when not using `knowledge_distilation` parameter.

This was my training script:
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 torchrun --nproc_per_node 8 --master_port 55001 \
	-m FlagEmbedding.finetune.embedder.encoder_only.m3 \
	--model_name_or_path BAAI/bge-m3 \
    --cache_dir ./cache/model \
    --train_data /data_x/EMBEDDING/DATA/data_mixed_241029/train.jsonl \
    --cache_path ./cache/data \
    --train_group_size 6 \
    --query_max_len 512 \
    --passage_max_len 4096 \
    --pad_to_multiple_of 8 \
    --knowledge_distillation False \
    --same_dataset_within_batch True \
    --output_dir ./MODELS/bge-ft-241031-loss=bge \
    --overwrite_output_dir \
    --learning_rate 1e-5 \
    --fp16 \
    --num_train_epochs 2 \
    --per_device_train_batch_size 2 \
    --dataloader_drop_last True \
    --warmup_ratio 0.1 \
    --gradient_checkpointing \
    --deepspeed FlagEmbedding/finetune/ds_stage0.json \
    --logging_steps 1 \
    --save_steps 1000 \
    --negatives_cross_device True \
    --temperature 0.02 \
    --sentence_pooling_method cls \
    --normalize_embeddings True \
    --kd_loss_type m3_kd_loss \
    --unified_finetuning True \
    --use_self_distill False \
    --fix_encoder False \
    --self_distill_start_step 0
```

And the error message looks like:
```
[rank7]: Traceback (most recent call last):
[rank7]:   File "<frozen runpy>", line 198, in _run_module_as_main
[rank7]:   File "<frozen runpy>", line 88, in _run_code
[rank7]:   File "/mnt/raid6/yjoonjang/FlagEmbedding/FlagEmbedding/finetune/embedder/encoder_only/m3/__main__.py", line 22, in <module>
[rank7]:     runner.run()
[rank7]:   File "/mnt/raid6/yjoonjang/FlagEmbedding/FlagEmbedding/abc/finetune/embedder/AbsRunner.py", line 119, in run
[rank7]:     self.trainer.train(resume_from_checkpoint=self.training_args.resume_from_checkpoint)
[rank7]:   File "/mnt/raid6/yjoonjang/miniconda3/envs/flagembedding/lib/python3.12/site-packages/transformers/trainer.py", line 1938, in train
[rank7]:     return inner_training_loop(
[rank7]:            ^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/mnt/raid6/yjoonjang/miniconda3/envs/flagembedding/lib/python3.12/site-packages/transformers/trainer.py", line 2236, in _inner_training_loop
[rank7]:     for step, inputs in enumerate(epoch_iterator):
[rank7]:                         ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/mnt/raid6/yjoonjang/miniconda3/envs/flagembedding/lib/python3.12/site-packages/accelerate/data_loader.py", line 550, in __iter__
[rank7]:     current_batch = next(dataloader_iter)
[rank7]:                     ^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/mnt/raid6/yjoonjang/miniconda3/envs/flagembedding/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank7]:     data = self._next_data()
[rank7]:            ^^^^^^^^^^^^^^^^^
[rank7]:   File "/mnt/raid6/yjoonjang/miniconda3/envs/flagembedding/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
[rank7]:     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
[rank7]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/mnt/raid6/yjoonjang/miniconda3/envs/flagembedding/lib/python3.12/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
[rank7]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank7]:             ~~~~~~~~~~~~^^^^^
[rank7]:   File "/mnt/raid6/yjoonjang/FlagEmbedding/FlagEmbedding/abc/finetune/embedder/AbsDataset.py", line 352, in __getitem__
[rank7]:     queries, passages, teacher_scores = self._create_batch_data(batch_raw_data=batch_data)
[rank7]:                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank7]:   File "/mnt/raid6/yjoonjang/FlagEmbedding/FlagEmbedding/abc/finetune/embedder/AbsDataset.py", line 419, in _create_batch_data
[rank7]:     if len(teacher_scores) > 0 and len(passages) > 0:
[rank7]:   
```

I looked at the code: FlagEmbedding/FlagEmbedding/abc/finetune/embedder/AbsDataset.py and found that a line should be needed in line 419 when not using knowledge distilation.
This is the original code:
```
passages.extend(tmp_passages)

                if len(teacher_scores) > 0 and len(passages) > 0:
                    assert len(teacher_scores) == len(passages)

        return queries, passages, teacher_scores
```

And this is the fixed code:
```
passages.extend(tmp_passages)

            if teacher_scores is not None:
                if len(teacher_scores) > 0 and len(passages) > 0:
                    assert len(teacher_scores) == len(passages)

        return queries, passages, teacher_scores
```

After adding this line, my script works well. 
Is it okay if I make a PR and add this bug?

Thank you.

**Comment by hanhainebula** [comment]
Thank you for finding this bug! You can submit a PR now, and then we will merge it.

**Comment by yjoonjang** [comment]
I opened a PR. 
It would be grateful if you could check this please.
