### ISSUE TITLE
New bug during fine-tune

### ISSUE THREAD

**Issue by holopyolo** [FlagOpen/FlagEmbedding#1178]
![image](https://github.com/user-attachments/assets/e7f250b2-95e1-46ba-8a9e-a0b6c18e82c6)
torchrun --nproc_per_node 1 \
	-m FlagEmbedding.finetune.reranker.encoder_only.base \
	--model_name_or_path BAAI/bge-reranker-v2-m3 \
    --cache_dir ./cache/model \
    --train_data ./train.json \
    --cache_path ./cache/data \
    --train_group_size 3 \
    --query_max_len 512 \
    --passage_max_len 512 \
    --pad_to_multiple_of 8 \
    --knowledge_distillation False \
	--output_dir ./model \
    --overwrite_output_dir \
    --learning_rate 6e-5 \
    --fp16 \
    --num_train_epochs 2 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 1 \
    --dataloader_drop_last True \
    --warmup_ratio 0.1 \
    --gradient_checkpointing \
    --weight_decay 0.01 \
    --deepspeed ../ds_stage0.json \
    --logging_steps 10 \
    --save_steps 500
    not reproducable on early versions

**Comment by yichuxue** [comment]
我也发现了这个问题
包版本
```
torch                    2.3.1
sentence-transformers    3.0.1
transformers             4.44.2
deepspeed                0.14.4
```

我训练时并没有使用flash-attn和deepspeed 
训练脚本
```shell
source /opt/conda/bin/activate /opt/conda/envs/bge
CUDA_VISIBLE_DEVICES=0,1
torchrun --nproc_per_node 2 \
	-m FlagEmbedding.finetune.embedder.encoder_only.m3 \
	--model_name_or_path BAAI/bge-m3 \
  --train_data /mnt/sda/app/embedding/train_data/embedding/20241024 \
  --output_dir /mnt/sda/app/embedding/train_out/embedding/20241024 \
  --train_group_size 8 \
  --query_max_len 256 \
  --passage_max_len 2048 \
  --pad_to_multiple_of 8 \
  --knowledge_distillation True \
  --same_dataset_within_batch True \
  --small_threshold 0 \
  --drop_threshold 0 \
  --overwrite_output_dir \
  --learning_rate 1e-5 \
  --fp16 \
  --num_train_epochs 2 \
  --per_device_train_batch_size 20 \
  --dataloader_drop_last True \
  --warmup_ratio 0.1 \
  --gradient_checkpointing \
  --logging_steps 1 \
  --save_steps 1000 \
  --negatives_cross_device True \
  --temperature 0.02 \
  --sentence_pooling_method cls \
  --normalize_embeddings True \
  --kd_loss_type m3_kd_loss \
  --unified_finetuning True \
  --use_self_distill True \
  --fix_encoder False \
  --self_distill_start_step 0
```
错误信息
```
[2024-11-01 07:09:35,232] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
[2024-11-01 07:09:35,356] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.3
 [WARNING]  using untested triton version (2.3.1), only 1.0.0 is known to be compatible
  0%|                                                                                                                                                    | 0/186 [00:00<?, ?it/s]You're using a XLMRobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/opt/conda/envs/bge/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
You're using a XLMRobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
/opt/conda/envs/bge/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:2888: UserWarning: `max_length` is ignored when `padding`=`True` and there is no truncation strategy. To pad to max length, use `padding='max_length'`.
  warnings.warn(
/opt/conda/envs/bge/lib/python3.10/site-packages/torch/utils/checkpoint.py:464: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/opt/conda/envs/bge/lib/python3.10/site-packages/torch/utils/checkpoint.py:464: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
[rank1]: Traceback (most recent call last):
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank1]:     return _run_code(code, main_globals, None,
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/runpy.py", line 86, in _run_code
[rank1]:     exec(code, run_globals)
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/FlagEmbedding/finetune/embedder/encoder_only/m3/__main__.py", line 22, in <module>
[rank1]:     runner.run()
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/FlagEmbedding/abc/finetune/embedder/AbsRunner.py", line 119, in run
[rank1]:     self.trainer.train(resume_from_checkpoint=self.training_args.resume_from_checkpoint)
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
[rank1]:     return inner_training_loop(
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
[rank1]:     tr_loss_step = self.training_step(model, inputs)
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/transformers/trainer.py", line 3349, in training_step
[rank1]:     self.accelerator.backward(loss, **kwargs)
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/accelerate/accelerator.py", line 2147, in backward
[rank1]:     self.scaler.scale(loss).backward(**kwargs)
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/torch/_tensor.py", line 525, in backward
[rank1]:     torch.autograd.backward(
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/torch/autograd/__init__.py", line 267, in backward
[rank1]:     _engine_run_backward(
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
[rank1]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/torch/autograd/function.py", line 301, in apply
[rank1]:     return user_fn(self, *args)
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 320, in backward
[rank1]:     torch.autograd.backward(outputs_with_grad, args_with_grad)
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/torch/autograd/__init__.py", line 267, in backward
[rank1]:     _engine_run_backward(
[rank1]:   File "/opt/conda/envs/bge/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
[rank1]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank1]: RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
[rank1]: Parameter at index 387 with name model.encoder.layer.23.output.LayerNorm.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
```

**Comment by 545999961** [comment]
> ```shell
> CUDA_VISIBLE_DEVICES=0,1
> torchrun --nproc_per_node 2 \
> 	-m FlagEmbedding.finetune.embedder.encoder_only.m3 \
> 	--model_name_or_path BAAI/bge-m3 \
>   --train_data /mnt/sda/app/embedding/train_data/embedding/20241024 \
>   --output_dir /mnt/sda/app/embedding/train_out/embedding/20241024 \
>   --train_group_size 8 \
>   --query_max_len 256 \
>   --passage_max_len 2048 \
>   --pad_to_multiple_of 8 \
>   --knowledge_distillation True \
>   --same_dataset_within_batch True \
>   --small_threshold 0 \
>   --drop_threshold 0 \
>   --overwrite_output_dir \
>   --learning_rate 1e-5 \
>   --fp16 \
>   --num_train_epochs 2 \
>   --per_device_train_batch_size 20 \
>   --dataloader_drop_last True \
>   --warmup_ratio 0.1 \
>   --gradient_checkpointing \
>   --logging_steps 1 \
>   --save_steps 1000 \
>   --negatives_cross_device True \
>   --temperature 0.02 \
>   --sentence_pooling_method cls \
>   --normalize_embeddings True \
>   --kd_loss_type m3_kd_loss \
>   --unified_finetuning True \
>   --use_self_distill True \
>   --fix_encoder False \
>   --self_distill_start_step 0
> ```

用gradient_checkpointing是需要和deepspeed搭配的，所以可以下载并传入deepspeed参数，或者去掉gradient_checkpointing

**Comment by yichuxue** [comment]
感谢！已经成功跑起来了。

**Comment by xushan116** [comment]
@yichuxue 同学请教一下  你跑这个bge-m3 finetune的环境都是什么版本呀？我现在也想跑这个 我现在用的
V100卡
cuda10.1(nvcc -V显式的是这个)或者是cuda12.0(nvidia-smi显式的是12.0) 
Pytho3.10 
torch2.5.1
transformers4.44.2
deepspeed 0.15.4
你能帮看下是哪里有问题吗
或者你列一下 你的所用的版本都是啥，感谢~~

**Comment by xushan116** [comment]
@yichuxue @545999961 
我现在也想微调bge-m3 我现在用的
V100卡
cuda10.1(nvcc -V显式的是这个)或者是cuda12.0(nvidia-smi显式的是12.0)
Pytho3.10
torch2.5.1
transformers4.44.2
deepspeed 0.15.4

能帮看下是哪里有问题吗,报错如下：
/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/transformers/deepspeed.py:24: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
NCCL version 2.21.5+cuda12.4
Using /root/.cache/torch_extensions/py310_cu124 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /root/.cache/torch_extensions/py310_cu124/fused_adam/build.ninja...
/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output multi_tensor_adam.cuda.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/TH -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 -std=c++17 -c /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
FAILED: multi_tensor_adam.cuda.o 
/usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output multi_tensor_adam.cuda.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/TH -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -O3 -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -lineinfo --use_fast_math -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 -std=c++17 -c /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/multi_tensor_adam.cu -o multi_tensor_adam.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[2/3] c++ -MMD -MF fused_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/TH -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -c /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp -o fused_adam_frontend.o 
FAILED: fused_adam_frontend.o 
c++ -MMD -MF fused_adam_frontend.o.d -DTORCH_EXTENSION_NAME=fused_adam -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/includes -I/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/adam -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/TH -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -O3 -std=c++17 -g -Wno-reorder -DVERSION_GE_1_1 -DVERSION_GE_1_3 -DVERSION_GE_1_5 -c /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp -o fused_adam_frontend.o 
In file included from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/ATen/core/TensorBase.h:14,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/ATen/core/TensorBody.h:38,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/ATen/Tensor.h:3,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/torch/extension.h:5,
                 from /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/csrc/adam/fused_adam_frontend.cpp:6:
/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/include/c10/util/C++17.h:13:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 9 or later."
 #error \
  ^~~~~
ninja: build stopped: subcommand failed.
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2104, in _run_ninja_build
[rank0]:     subprocess.run(
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/subprocess.py", line 526, in run
[rank0]:     raise CalledProcessError(retcode, process.args,
[rank0]: subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/FlagEmbedding/finetune/embedder/encoder_only/m3/__main__.py", line 22, in <module>
[rank0]:     runner.run()
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/FlagEmbedding/abc/finetune/embedder/AbsRunner.py", line 119, in run
[rank0]:     self.trainer.train(resume_from_checkpoint=self.training_args.resume_from_checkpoint)
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/transformers/trainer.py", line 2098, in _inner_training_loop
[rank0]:     model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1323, in prepare
[rank0]:     result = self._prepare_deepspeed(*args)
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1842, in _prepare_deepspeed
[rank0]:     engine, optimizer, _, lr_scheduler = ds_initialize(**kwargs)
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/__init__.py", line 193, in initialize
[rank0]:     engine = DeepSpeedEngine(args=args,
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 313, in __init__
[rank0]:     self._configure_optimizer(optimizer, model_parameters)
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1276, in _configure_optimizer
[rank0]:     basic_optimizer = self._configure_basic_optimizer(model_parameters)
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1353, in _configure_basic_optimizer
[rank0]:     optimizer = FusedAdam(
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/adam/fused_adam.py", line 94, in __init__
[rank0]:     fused_adam_cuda = FusedAdamBuilder().load()
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 531, in load
[rank0]:     return self.jit_load(verbose)
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/deepspeed/ops/op_builder/builder.py", line 578, in jit_load
[rank0]:     op_module = load(name=self.name,
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packorch/utils/cpp_extension.py", line 1314, in load
[rank0]:     return _jit_compile(
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1721, in _jit_compile
[rank0]:     _write_ninja_file_and_build_library(
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1833, in _write_ninja_file_and_build_library
[rank0]:     _run_ninja_build(
[rank0]:   File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2120, in _run_ninja_build
[rank0]:     raise RuntimeError(message) from e
[rank0]: RuntimeError: Error building extension 'fused_adam'
ages/t[rank0]:[W1118 19:39:23.948438280 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
E1118 19:39:25.875000 6762 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 6813) of binary: /root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/bin/python
Traceback (most recent call last):
  File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/paddlejob/workspace/xushan04/env_for_bge/yinxiang_py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
FlagEmbedding.finetune.embedder.encoder_only.m3 FAILED
------------------------------------------------------------


或者列一下 你的所用的版本都是啥，感谢~~

**Comment by xushan116** [comment]
@yichuxue 还有就是问一下 你是不使用deepspeed嘛  求教求教

**Comment by yichuxue** [comment]
是的，我是这样跑起来的。

**Comment by xushan116** [comment]
@yichuxue 再请教一下，你知道train_group_size这个参数是什么含义吗？怎么设置？
还有就是需要用它给的脚本将文章按照不同长度划分吗，如果划分的话训练时参数设置有什么不一样吗？还是划分了就能直接用？
