### ISSUE TITLE
There appear to be 2 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d '

### ISSUE THREAD

**Issue by dbcSep03** [FlagOpen/FlagEmbedding#1187]
I have 2 RTX4090,when inference, have a bug.
The code is below:
```
from FlagEmbedding import BGEM3FlagModel
import os
if __name__ == "__main__":
    model = BGEM3FlagModel('weights/bge-m3',  
                        use_fp16=True) # Setting use_fp16 to True speeds up computation with a slight performance degradation

    sentences_1 = ["What is BGE M3?", "Defination of BM25"]
    sentences_2 = ["BGE M3 is an embedding model supporting dense retrieval, lexical matching and multi-vector interaction.", 
                "BM25 is a bag-of-words retrieval function that ranks a set of documents based on the query terms appearing in each document"]

    embeddings_1 = model.encode(sentences_1, 
                                batch_size=12, 
                                max_length=8192, # If you don't need such a long length, you can set a smaller value to speed up the encoding process.
                                )['dense_vecs']
    embeddings_2 = model.encode(sentences_2)['dense_vecs']
    similarity = embeddings_1 @ embeddings_2.T
    print(similarity)
    # [[0.6265, 0.3477], [0.3499, 0.678 ]]
```
when run, it will apear
```
  File "/home/dongbingcheng/anaconda3/envs/dqa/lib/python3.10/site-packages/FlagEmbedding/abc/inference/AbsEmbedder.py", line 352, in stop_multi_process_pool
  File "/home/dongbingcheng/anaconda3/envs/dqa/lib/python3.10/multiprocessing/process.py", line 133, in terminate
  File "/home/dongbingcheng/anaconda3/envs/dqa/lib/python3.10/multiprocessing/popen_fork.py", line 57, in terminate
AttributeError: 'NoneType' object has no attribute 'SIGTERM'
/home/dongbingcheng/anaconda3/envs/dqa/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
but i set ``os.environ["CUDA_VISIBLE_DEVICES"] = '0'``,the problem disappears. 
because i want to train in two GPUs, so i want to know how to fix it.
Thank you!

**Comment by 545999961** [comment]
This was caused by not deleting the model pool. You can use `del model` after inference, or you can put the code in another function and call this function in the `__main__` block. Actually, this is only an error message at the end of the code, and it will have no influence on the program's execution.

**Comment by dbcSep03** [comment]
Thank you

**Comment by daje0601** [comment]
I'm getting the exact same error.
I simply used the code from FlagEmbedding, so why am I getting this error?
```
python scripts/hn_mine.py   --model_name_or_path BAAI/bge-m3   --input_file ./before_data.jsonl   --output_file ./after_data.jsonl   --range_for_sampling 3-20   --negative_number 5   --use_gpu_for_searching 
```

As you say, the code has the data in it, but I'm wondering why I'm getting this error.
This error messages:
```
Batches: 100%|█████████████████████████████████████████████████████████████████| 11639/11639 [00:55<00:00, 211.32it/s]
Exception ignored in: <function AbsEmbedder.__del__ at 0x782090d994e0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/FlagEmbedding/abc/inference/AbsEmbedder.py", line 258, in __del__
  File "/usr/local/lib/python3.11/dist-packages/FlagEmbedding/abc/inference/AbsEmbedder.py", line 350, in stop_multi_process_pool
  File "/usr/lib/python3.11/multiprocessing/process.py", line 133, in terminate
  File "/usr/lib/python3.11/multiprocessing/popen_fork.py", line 57, in terminate
AttributeError: 'NoneType' object has no attribute 'SIGTERM'
/usr/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

> This was caused by not deleting the model pool. You can use `del model` after inference, or you can put the code in another function and call this function in the `__main__` block. Actually, this is only an error message at the end of the code, and it will have no influence on the program's execution.

**Comment by 545999961** [comment]
> I'm getting the exact same error. I simply used the code from FlagEmbedding, so why am I getting this error?
> 
> ```
> python scripts/hn_mine.py   --model_name_or_path BAAI/bge-m3   --input_file ./before_data.jsonl   --output_file ./after_data.jsonl   --range_for_sampling 3-20   --negative_number 5   --use_gpu_for_searching 
> ```
> 
> As you say, the code has the data in it, but I'm wondering why I'm getting this error. This error messages:
> 
> ```
> Batches: 100%|█████████████████████████████████████████████████████████████████| 11639/11639 [00:55<00:00, 211.32it/s]
> Exception ignored in: <function AbsEmbedder.__del__ at 0x782090d994e0>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/dist-packages/FlagEmbedding/abc/inference/AbsEmbedder.py", line 258, in __del__
>   File "/usr/local/lib/python3.11/dist-packages/FlagEmbedding/abc/inference/AbsEmbedder.py", line 350, in stop_multi_process_pool
>   File "/usr/lib/python3.11/multiprocessing/process.py", line 133, in terminate
>   File "/usr/lib/python3.11/multiprocessing/popen_fork.py", line 57, in terminate
> AttributeError: 'NoneType' object has no attribute 'SIGTERM'
> /usr/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
>   warnings.warn('resource_tracker: There appear to be %d '
> ```
> 
> > This was caused by not deleting the model pool. You can use `del model` after inference, or you can put the code in another function and call this function in the `__main__` block. Actually, this is only an error message at the end of the code, and it will have no influence on the program's execution.

To facilitate inference, a multiprocessing pool has been introduced in the model. In the code, this pool is set to be deleted when the model is deleted. If this function is not called, it will trigger this error, although it does not actually affect any operations.
