### ISSUE TITLE
Windows系统训练Embedding模型，保存模型文件时报错

### ISSUE THREAD

**Issue by StephenZKCurry** [FlagOpen/FlagEmbedding#1207]
Windows系统上训练bge-m3模型，模型训练成功，但是在保存模型文件时会报错，不知道是什么原因，报错信息如下：
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python_space\thor\venv\Lib\site-packages\FlagEmbedding\baai_general_embedding\finetune\run.py", line 111, in <module>
    main()
  File "D:\python_space\thor\venv\Lib\site-packages\FlagEmbedding\baai_general_embedding\finetune\run.py", line 103, in main
    trainer.save_model()
  File "D:\python_space\thor\venv\Lib\site-packages\transformers\trainer.py", line 3454, in save_model
    self._save(output_dir)
  File "D:\python_space\thor\venv\Lib\site-packages\FlagEmbedding\baai_general_embedding\finetune\trainer.py", line 36, in _save
    save_ckpt_for_sentence_transformers(output_dir,
  File "D:\python_space\thor\venv\Lib\site-packages\FlagEmbedding\baai_general_embedding\finetune\trainer.py", line 13, in save_ckpt_for_sentence_transformers
    model.save(ckpt_dir)
  File "D:\python_space\thor\venv\Lib\site-packages\sentence_transformers\SentenceTransformer.py", line 1139, in save
    module.save(model_path, safe_serialization=safe_serialization)
  File "D:\python_space\thor\venv\Lib\site-packages\sentence_transformers\models\Transformer.py", line 180, in save
    self.auto_model.save_pretrained(output_path, safe_serialization=safe_serialization)
  File "D:\python_space\thor\venv\Lib\site-packages\transformers\modeling_utils.py", line 2793, in save_pretrained
    safe_save_file(shard, os.path.join(save_directory, shard_file), metadata={"format": "pt"})
  File "D:\python_space\thor\venv\Lib\site-packages\safetensors\torch.py", line 286, in save_file
    serialize_file(_flatten(tensors), filename, metadata=metadata)
safetensors_rust.SafetensorError: Error while serializing: IoError(Os { code: 1224, kind: Uncategorized, message: "请求的操作无法在使用用户映射区域打开的文件上执行。" })
```

训练语句如下：
```shell
python -m FlagEmbedding.baai_general_embedding.finetune.run --output_dir D:/llm_weights/bge-m3_finetune --model_name_or_path D:/llm_weights/bge-m3 --train_data D:/python_space/thor/train_dataset.jsonl --learning_rate 1e-5 --fp16 --num_train_epochs 1 --per_device_train_batch_size 1 --gradient_accumulation_steps 32 --dataloader_drop_last True --normlized True --temperature 0.01 --query_max_len 256 --passage_max_len 512 --train_group_size 6 --logging_steps 10 --logging_strategy steps --report_to tensorboard --save_strategy no
```

相关库版本：
> torch: 2.3.1
safetensors: 0.4.5
FlagEmbedding: 1.2.10

**Comment by hanhainebula** [comment]
你好，@StephenZKCurry！这个错误我们没有遇到过，抱歉不能提供一些建议。我们最近发布了新版本的 FlagEmbedding，可以尝试下新版本的 m3 的训练代码，看是否还是会报这个错误，欢迎提供反馈！

**Comment by StephenZKCurry** [comment]
@hotchpotch 您好，我这边初步排查了一下报错原因，发现是在`FlagEmbedding.baai_general_embedding.finetune.trainer.BiTrainer._save()`函数中会保存**model.safetensors**文件两次，第一次是调用`self.model.save(output_dir)`，第二次是调用`save_ckpt_for_sentence_transformers(output_dir,pooling_mode=self.args.sentence_pooling_method, normlized=self.args.normlized)`。其中`save_ckpt_for_sentence_transformers()`函数中会首先调用`models.Transformer(ckpt_dir)`加载第一次保存的**model.safetensors**文件，导致该文件被占用，在执行之后的`model.save(ckpt_dir)`时再次保存同名的模型文件触发了异常。
最新版本FlagEmbedding的训练代码中已经将`save_ckpt_for_sentence_transformers()`注释掉了，是出于什么原因呢，注释掉之后应该是不会出现这个报错了。
![image](https://github.com/user-attachments/assets/7dd646d5-0708-4021-8dff-b256fd9ee4f7)

**Comment by StephenZKCurry** [comment]
@hanhainebula 您好，我使用最新版本的FlagEmbedding 1.3.2执行了bge-m3模型的训练命令，报了下面的异常，看样子和分布式训练有关系
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python_space\thor\venv\Lib\site-packages\FlagEmbedding\finetune\embedder\encoder_only\m3\__main__.py", line 17, in <module>
    train_dataset = AbsEmbedderTrainDataset(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_space\thor\venv\Lib\site-packages\FlagEmbedding\abc\finetune\embedder\AbsDataset.py", line 37, in __init__
    temp_dataset = self._load_dataset(data_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python_space\thor\venv\Lib\site-packages\FlagEmbedding\abc\finetune\embedder\AbsDataset.py", line 49, in _load_dataset
    if dist.get_rank() == 0:
       ^^^^^^^^^^^^^^^
  File "D:\python_space\thor\venv\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1746, in get_rank
    default_pg = _get_default_group()
                 ^^^^^^^^^^^^^^^^^^^^
  File "D:\python_space\thor\venv\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1008, in _get_default_group
    raise ValueError(
ValueError: Default process group has not been initialized, please make sure to call init_process_group.
```
执行的训练命令如下：
```
python -m FlagEmbedding.finetune.embedder.encoder_only.m3 --output_dir D:/llm_weights/bge-m3_finetune --model_name_or_path D:/llm_weights/bge-m3 --train_data D:/python_space/thor/train_dataset.jsonl --learning_rate 1e-5 --fp16 --num_train_epochs 1 --per_device_train_batch_size 4 --gradient_accumulation_steps 32 --dataloader_drop_last True --normalize_embeddings True --kd_loss_type m3_kd_loss --gradient_checkpointing --unified_finetuning True --temperature 0.01 --query_max_len 256 --passage_max_len 512 --train_group_size 6 --logging_steps 10 --logging_strategy steps --report_to tensorboard --save_strategy no
```
不知道是否有参数可以切换为单机训练模式

**Comment by hanhainebula** [comment]
你好，@StephenZKCurry！请参考我们[这里给出的例子](https://github.com/FlagOpen/FlagEmbedding/blob/master/examples/finetune/embedder/encoder_only/m3_same_dataset.sh)启动训练，可以看下使用 torchrun 而不是直接使用 python 启动训练会不会解决这个问题。

**Comment by hanhainebula** [comment]
> > 你好，@StephenZKCurry！请参考我们[这里给出的例子](https://github.com/FlagOpen/FlagEmbedding/blob/master/examples/finetune/embedder/encoder_only/m3_same_dataset.sh)启动训练，可以看下使用 torchrun 而不是直接使用 python 启动训练会不会解决这个问题。
> 
> 您好，我是在Windows系统上执行的训练，可能是系统不支持NCCL库的原因，使用torchrun命令会报错，所以才改用的python命令执行训练

那可以尝试克隆仓库到本地然后用 `pip install -e .` 安装，再把对应报错的代码 `dist.get_rank()` 给删掉试一试。

**Comment by StephenZKCurry** [comment]
> > > 你好，@StephenZKCurry！请参考我们[这里给出的例子](https://github.com/FlagOpen/FlagEmbedding/blob/master/examples/finetune/embedder/encoder_only/m3_same_dataset.sh)启动训练，可以看下使用 torchrun 而不是直接使用 python 启动训练会不会解决这个问题。
> > 
> > 
> > 您好，我是在Windows系统上执行的训练，可能是系统不支持NCCL库的原因，使用torchrun命令会报错，所以才改用的python命令执行训练
> 
> 那可以尝试克隆仓库到本地然后用 `pip install -e .` 安装，再把对应报错的代码 `dist.get_rank()` 给删掉试一试。

嗯嗯，删掉`dist.get_rank()`这块的判断之后就可以正常运行训练了。
