### ISSUE TITLE
Error occurred when running hard negative mining

### ISSUE THREAD

**Issue by wongbokhe1** [FlagOpen/FlagEmbedding#1226]
python hn_mine.py --model_name_or_path /data/bxhuang/model_folder/xiaobu-embedding-v2 --input_file /data/bxhuang/Reranking/train_data/text_pairs.json --output_file /data/bxhuang/Reranking/train_data/text_pairs_HN.json --range_for_sampling 50-80 --negative_number 15 --use_gpu_for_searching

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/bxhuang/FlagEmbedding/scripts/hn_mine.py", line 8, in <module>
    from FlagEmbedding import FlagModel
  File "/root/miniconda3/lib/python3.12/site-packages/FlagEmbedding/__init__.py", line 1, in <module>
    from .inference import *
  File "/root/miniconda3/lib/python3.12/site-packages/FlagEmbedding/inference/__init__.py", line 1, in <module>
    from .auto_embedder import FlagAutoModel
  File "/root/miniconda3/lib/python3.12/site-packages/FlagEmbedding/inference/auto_embedder.py", line 5, in <module>
    from FlagEmbedding.inference.embedder.model_mapping import (
  File "/root/miniconda3/lib/python3.12/site-packages/FlagEmbedding/inference/embedder/__init__.py", line 1, in <module>
    from .encoder_only import FlagModel, BGEM3FlagModel
  File "/root/miniconda3/lib/python3.12/site-packages/FlagEmbedding/inference/embedder/encoder_only/__init__.py", line 2, in <module>
    from .m3 import M3Embedder as BGEM3FlagModel
  File "/root/miniconda3/lib/python3.12/site-packages/FlagEmbedding/inference/embedder/encoder_only/m3.py", line 13, in <module>
    from FlagEmbedding.finetune.embedder.encoder_only.m3 import (
  File "/root/miniconda3/lib/python3.12/site-packages/FlagEmbedding/finetune/embedder/encoder_only/m3/__init__.py", line 1, in <module>
    from FlagEmbedding.abc.finetune.embedder import AbsEmbedderDataArguments as EncoderOnlyEmbedderM3DataArguments
  File "/root/miniconda3/lib/python3.12/site-packages/FlagEmbedding/abc/finetune/embedder/__init__.py", line 6, in <module>
    from .AbsDataset import (
  File "/root/miniconda3/lib/python3.12/site-packages/FlagEmbedding/abc/finetune/embedder/AbsDataset.py", line 10, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1412, in _handle_fromlist
  File "/root/miniconda3/lib/python3.12/site-packages/transformers/utils/import_utils.py", line 1766, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/transformers/utils/import_utils.py", line 1780, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.data.data_collator because of the following error (look up to see its traceback):
maximum recursion depth exceeded

**Comment by hanhainebula** [comment]
Hello, @wongbokhe1. You can remove `--use_gpu_for_searching` from the command, or refer to [here](https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/evaluation#requirements) to install faiss-gpu.

**Comment by wongbokhe1** [comment]
> Hello, @wongbokhe1. You can remove `--use_gpu_for_searching` from the command, or refer to [here](https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/evaluation#requirements) to install faiss-gpu.

**Thanks a lot! After solving the faiss-gpu problem, a new error related to 'AbsEmbedder.py' occur:**
Exception ignored in: <function AbsEmbedder.__del__ at 0x7f6bfdd130a0>
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/FlagEmbedding/abc/inference/AbsEmbedder.py", line 260, in __del__
  File "/root/miniconda3/lib/python3.10/site-packages/FlagEmbedding/abc/inference/AbsEmbedder.py", line 352, in stop_multi_process_pool
  File "/root/miniconda3/lib/python3.10/multiprocessing/process.py", line 133, in terminate
  File "/root/miniconda3/lib/python3.10/multiprocessing/popen_fork.py", line 57, in terminate
AttributeError: 'NoneType' object has no attribute 'SIGTERM'
/root/miniconda3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by hanhainebula** [comment]
> > Hello, @wongbokhe1. You can remove `--use_gpu_for_searching` from the command, or refer to [here](https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/evaluation#requirements) to install faiss-gpu.
> 
> **Thanks a lot! After solving the faiss-gpu problem, a new error related to 'AbsEmbedder.py' occur:** Exception ignored in: <function AbsEmbedder.**del** at 0x7f6bfdd130a0> Traceback (most recent call last): File "/root/miniconda3/lib/python3.10/site-packages/FlagEmbedding/abc/inference/AbsEmbedder.py", line 260, in **del** File "/root/miniconda3/lib/python3.10/site-packages/FlagEmbedding/abc/inference/AbsEmbedder.py", line 352, in stop_multi_process_pool File "/root/miniconda3/lib/python3.10/multiprocessing/process.py", line 133, in terminate File "/root/miniconda3/lib/python3.10/multiprocessing/popen_fork.py", line 57, in terminate AttributeError: 'NoneType' object has no attribute 'SIGTERM' /root/miniconda3/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown warnings.warn('resource_tracker: There appear to be %d '

Please refer to: https://github.com/FlagOpen/FlagEmbedding/issues/1187#issuecomment-2458871182
