### ISSUE TITLE
Finetune stop with error after some iterations

### ISSUE THREAD

**Issue by dviettu134** [FlagOpen/FlagEmbedding#1239]
I run finetuning on my server and it get error after ~300 iterations.

My run command:
```
torchrun --nproc_per_node 2 \
    -m FlagEmbedding.finetune.embedder.encoder_only.m3 \
    --model_name_or_path BAAI/bge-m3 \
    --cache_dir ./cache/model \
    --train_data /home/ars/bge_m3/data/postprocessed_training_bge_m3_data_score.jsonl \
    --cache_path ./cache/data \
    --train_group_size 8 \
    --query_max_len 192 \
    --passage_max_len 392 \
    --pad_to_multiple_of 8 \
    --knowledge_distillation True \
    --same_dataset_within_batch True \
    --small_threshold 0 \
    --drop_threshold 0 \
    --output_dir ./test_encoder_only_m3_bge-m3_sd \
    --overwrite_output_dir \
    --learning_rate 1e-5 \
    --fp16 \
    --num_train_epochs 8 \
    --per_device_train_batch_size 1 \
    --dataloader_drop_last True \
    --warmup_ratio 0.1 \
    --gradient_checkpointing \
    --deepspeed /home/ars/bge_m3/FlagEmbedding/examples/finetune/ds_stage0.json \
    --logging_steps 1 \
    --save_steps 20000 \
    --negatives_cross_device False\
    --temperature 0.02 \
    --sentence_pooling_method cls \
    --normalize_embeddings True \
    --kd_loss_type m3_kd_loss \
    --unified_finetuning False \
    --fix_encoder False \
    --use_self_distill True \
    --self_distill_start_step 0
```

The error log:
```
{'loss': 0.0021, 'grad_norm': 0.49594647181279233, 'learning_rate': 6.433126179652261e-06, 'epoch': 0.04}                                                                                                                       
{'loss': 0.9388, 'grad_norm': 132.38355732491857, 'learning_rate': 6.437283506961173e-06, 'epoch': 0.04}                                                                                                                        
{'loss': 1.497, 'grad_norm': 172.36578224991467, 'learning_rate': 6.441425798695444e-06, 'epoch': 0.04}                                                                                                                         
{'loss': 0.4784, 'grad_norm': 127.2197018510203, 'learning_rate': 6.44555316321993e-06, 'epoch': 0.04}                                                                                                                          
{'loss': 0.1182, 'grad_norm': 24.6498637661835, 'learning_rate': 6.449665707732172e-06, 'epoch': 0.04}                                                                                                                          
  0%|▊                                                                                                                                                                                    | 283/61912 [01:58<7:06:04,  2.41it/s][rank0]: Traceback (most recent call last):
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/FlagEmbedding/finetune/embedder/encoder_only/m3/__main__.py", line 22, in <module>
[rank0]:     runner.run()
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/FlagEmbedding/abc/finetune/embedder/AbsRunner.py", line 119, in run
[rank0]:     self.trainer.train(resume_from_checkpoint=self.training_args.resume_from_checkpoint)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/transformers/trainer.py", line 2279, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/transformers/trainer.py", line 3349, in training_step
[rank0]:     self.accelerator.backward(loss, **kwargs)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/accelerate/accelerator.py", line 2233, in backward
[rank0]:     self.deepspeed_engine_wrapped.backward(loss, **kwargs)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 186, in backward
[rank0]:     self.engine.backward(loss, **kwargs)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 18, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 2059, in backward
[rank0]:     self.optimizer.backward(loss, retain_graph=retain_graph)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/deepspeed/runtime/fp16/fused_optimizer.py", line 383, in backward
[rank0]:     scaled_loss.backward(create_graph=create_graph, retain_graph=retain_graph)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/_tensor.py", line 521, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/autograd/function.py", line 306, in apply
[rank0]:     return user_fn(self, *args)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 313, in backward
[rank0]:     torch.autograd.backward(outputs_with_grad, args_with_grad)
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/autograd/__init__.py", line 289, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/autograd/graph.py", line 768, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]: RuntimeError: t == DeviceType::CUDA INTERNAL ASSERT FAILED at "../c10/cuda/impl/CUDAGuardImpl.h":28, please report a bug to PyTorch. 
  0%|          | 283/61912 [01:58<7:11:36,  2.38it/s]                                                                                                                                                                           
[rank0]:[W1118 10:44:55.754268322 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
W1118 10:44:56.295000 140533229486720 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 10974 closing signal SIGTERM
E1118 10:44:56.359000 140533229486720 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 10973) of binary: /home/admin/anaconda3/envs/bge_m3/bin/python
Traceback (most recent call last):
  File "/home/admin/anaconda3/envs/bge_m3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/admin/anaconda3/envs/bge_m3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
FlagEmbedding.finetune.embedder.encoder_only.m3 FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-18_10:44:56
  host      : admin-server
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 10973)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by hanhainebula** [comment]
Hello, @dviettu134. This error seems to be a problem of machine. You can try to rerun the command or check your machine.

**Comment by dviettu134** [comment]
@hanhainebula it looks like the GPU is OOM at some points.
Thank you for your comment, I'm closing this issue.
