### ISSUE TITLE
加载本地的数据，对嵌入模型进行测评，报错

### ISSUE THREAD

**Issue by chaoStart** [FlagOpen/FlagEmbedding#1243]
![企业微信截图_17319963789656](https://github.com/user-attachments/assets/a582d7cf-6822-4928-bd62-12db8158b787)

Traceback (most recent call last):
  File "/home/bqc/project/evalscope/MTEBtest.py", line 30, in <module>
    evaluation.run(model, output_folder="BAAI",verbosity=2,eval_splits=["test"])
  File "/home/bqc/.conda/envs/evalscope/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 477, in run
    raise e
  File "/home/bqc/.conda/envs/evalscope/lib/python3.10/site-packages/mteb/evaluation/MTEB.py", line 407, in run
    task.load_data(eval_splits=task_eval_splits, **kwargs)
  File "/home/bqc/.conda/envs/evalscope/lib/python3.10/site-packages/mteb/tasks/Retrieval/zho/CMTEBRetrieval.py", line 72, in load_data
    self.corpus, self.queries, self.relevant_docs = load_retrieval_data(
  File "/home/bqc/.conda/envs/evalscope/lib/python3.10/site-packages/mteb/tasks/Retrieval/zho/CMTEBRetrieval.py", line 15, in load_retrieval_data
    qrels = load_dataset(dataset_path + "-qrels", revision=qrel_revision)[eval_split]
  File "/home/bqc/.conda/envs/evalscope/lib/python3.10/site-packages/datasets/load.py", line 2074, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/bqc/.conda/envs/evalscope/lib/python3.10/site-packages/datasets/load.py", line 1795, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/bqc/.conda/envs/evalscope/lib/python3.10/site-packages/datasets/load.py", line 1677, in dataset_module_factory
    raise FileNotFoundError(f"Couldn't find any data file at {relative_to_absolute_path(path)}.")
FileNotFoundError: Couldn't find any data file at /home/bqc/.cache/evalscope/dataset/T2Retrieval-qrels.

**Comment by chaoStart** [comment]
import sys
sys.path.append('/home/bqc/project/evalscope')
# from Modelscope import ModelScopeEmbeddings
from sentence_transformers import SentenceTransformer
model_name = "BAAI/bge-base-en-v1.5"
model = SentenceTransformer(model_name_or_path="/home/bqc/xinference_LLM/bge-large-zh-v1.5",local_files_only=True)
# 证明嵌入可以正常调用，维度是1024，模式是bge-large-zh
sentences = [
    "The weather is lovely today.",
    "It's so sunny outside!",
    "He drove to the stadium.",
]
embeddings = model.encode(sentences)
print(embeddings.shape)
similarities = model.similarity(embeddings, embeddings)
print(similarities)

print("根据huggingFace的MTEB数据集进行测试")

if __name__ == '__main__':
    # model_id = "iic/nlp_gte_sentence-embedding_chinese-large"
    # model = ModelScopeEmbeddings(model_id=model_id, model_revision="v1.0.0")
    import mteb
    from mteb import MTEB
    ChineseTaskList = ["T2Retrieval"]
    tasks = mteb.get_tasks(tasks=ChineseTaskList)

    for task in tasks:
        evaluation = MTEB(tasks=[task])
        evaluation.run(model,output_folder=f"zh_results/{model_name}",verbosity=2,eval_splits=["test"])

**Comment by hanhainebula** [comment]
你好，@chaoStart。可以参考我们在这里提供的示例进行评测：https://github.com/FlagOpen/FlagEmbedding/tree/master/examples/evaluation#1-MTEB

如果因为网络问题无法访问 huggingface.co，可以设置环境变量 HF_ENDPOINT 为 hf-mirror.com 来从镜像加载数据。

**Comment by chaoStart** [comment]
已经解决问题了！如果把数据集下载到本地，从本地加载数据集retriever数据集合，需要下载2个数据数据集，另一个qres数据集；注意这里的路径需要修改为本地的路径
