### ISSUE TITLE
bge-multilingual-gemma2在多卡机器上部署报错

### ISSUE THREAD

**Issue by Yao990x16** [FlagOpen/FlagEmbedding#1292]
我的机器是8张T4显卡，部署脚本的代码如下：
import os
import torch
import uvicorn
from pydantic import BaseModel
from fastapi.middleware.cors import CORSMiddleware
from typing import List, Union
from fastapi import FastAPI, HTTPException
from sentence_transformers import SentenceTransformer
import numpy as np
import tiktoken

app = FastAPI()

# CORS 允许所有源
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 设置 PyTorch 显存分配配置，防止显存碎片化
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'

# 请求数据结构
class EmbeddingProcessRequest(BaseModel):
    input: List[str]
    model: str

class EmbeddingQuestionRequest(BaseModel):
    input: str
    model: str

class EmbeddingResponse(BaseModel):
    data: list
    model: str
    object: str
    usage: dict

# Token 计算函数
def num_tokens_from_string(string: str) -> int:
    encoding = tiktoken.get_encoding('cl100k_base')
    return len(encoding.encode(string))

# Min-Max 归一化
def min_max_normalize(embedding):
    return (embedding - np.min(embedding)) / (np.max(embedding) - np.min(embedding)) if np.max(embedding) != np.min(embedding) else embedding

@app.post("/v1/embeddings", response_model=EmbeddingResponse)
async def get_embeddings(request: Union[EmbeddingProcessRequest, EmbeddingQuestionRequest]):
    # 根据请求类型处理输入
    if isinstance(request, EmbeddingProcessRequest): 
        payload = request.input
    elif isinstance(request, EmbeddingQuestionRequest): 
        payload = [request.input]
    else:
        raise HTTPException(status_code=400, detail="Invalid input type")

    # 生成嵌入
    embeddings = [embeddings_model.encode(text, show_progress_bar=False) for text in payload]

    # 对每个嵌入向量进行 Min-Max 归一化
    embeddings = [min_max_normalize(embedding) for embedding in embeddings]
    
    # 转换嵌入为列表
    embeddings = [embedding.tolist() for embedding in embeddings]

    # Token计算
    prompt_tokens = sum(len(text.split()) for text in payload)
    total_tokens = sum(num_tokens_from_string(text) for text in payload)

    # 返回兼容 OpenAI 的格式
    response = {
        "data": [
            {
                "embedding": embedding,
                "index": index,
                "object": "embedding"
            } for index, embedding in enumerate(embeddings)
        ],
        "model": request.model,
        "object": "list",
        "usage": {
            "prompt_tokens": prompt_tokens,
            "total_tokens": total_tokens,
        }
    }

    return response

if __name__ == "__main__":
    # 模型路径
    MODEL_PATH = "/home/Downloads/hf/BAAI/bge-gemma2"

    # 加载模型并设置多卡支持
    embeddings_model = SentenceTransformer(
        MODEL_PATH,
        model_kwargs={
            "torch_dtype": torch.float16,  # 使用半精度减少显存占用
            "device_map": "auto"           # 自动分配权重到所有 GPU
        }
    )

    print("Model loaded successfully.")

    # 启动 FastAPI 服务
    uvicorn.run(app, host='0.0.0.0', port=6006, workers=1)

------------------------------------------------------------------------------------------------------------------------------------
运行该脚本后报错信息如下：
Loading model with multi-GPU support...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████| 4/4 [00:11<00:00,  2.77s/it]
Traceback (most recent call last):
  File "deploy.py", line 98, in <module>
    embeddings_model = SentenceTransformer(
  File "/root/anaconda3/envs/bge/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 345, in __init__
    self.to(device)
  File "/root/anaconda3/envs/bge/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/root/anaconda3/envs/bge/lib/python3.8/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/bge/lib/python3.8/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/root/anaconda3/envs/bge/lib/python3.8/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/root/anaconda3/envs/bge/lib/python3.8/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/root/anaconda3/envs/bge/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 98.00 MiB. GPU 0 has a total capacity of 14.58 GiB of which 16.81 MiB is free. Including non-PyTorch memory, this process has 14.55 GiB memory in use. Of the allocated memory 14.44 GiB is allocated by PyTorch, and 3.04 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
--------------------------------------------------------------------------------------------------------------------------------------------------
gpu占用情况如下:gpu0上显存占用突然增大导致错误
![image](https://github.com/user-attachments/assets/f339191c-df1e-4dd1-ac06-830588f810a5)

**Comment by 545999961** [comment]
可以尝试减小编码时候的batch size

**Comment by Yao990x16** [comment]
> 看起来模型部署的时候就OOM了，GPU是多大内存呢，看起来好像不足够加载模型

16G，8卡T4

**Comment by 545999961** [comment]
> > 看起来模型部署的时候就OOM了，GPU是多大内存呢，看起来好像不足够加载模型
> 
> 16G，8卡T4

可以修改下源码，在加载`AutoModel.from_pretrained`的时候引入参数`torch_dtype=torch.float16`
