### ISSUE TITLE
Python38下微调bge-reranker-v2-m3报错

### ISSUE THREAD

**Issue by DrDavidS** [FlagOpen/FlagEmbedding#1299]
看起来是3.8不支持list的typehint导致的

```
bin /opt/conda/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.0
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /opt/conda/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda121.so...
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/conda/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/conda/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/conda/lib/python3.8/site-packages/FlagEmbedding/finetune/reranker/encoder_only/base/__init__.py", line 1, in <module>
    from .modeling import CrossEncoderModel
  File "/opt/conda/lib/python3.8/site-packages/FlagEmbedding/finetune/reranker/encoder_only/base/modeling.py", line 4, in <module>
    from FlagEmbedding.abc.finetune.reranker import AbsRerankerModel
  File "/opt/conda/lib/python3.8/site-packages/FlagEmbedding/abc/finetune/reranker/__init__.py", line 2, in <module>
    from .AbsDataset import (
  File "/opt/conda/lib/python3.8/site-packages/FlagEmbedding/abc/finetune/reranker/AbsDataset.py", line 179, in <module>
    class AbsRerankerCollator(DataCollatorWithPadding):
  File "/opt/conda/lib/python3.8/site-packages/FlagEmbedding/abc/finetune/reranker/AbsDataset.py", line 186, in AbsRerankerCollator
    def __call__(self, features) -> list[BatchEncoding]:
TypeError: 'type' object is not subscriptable
[2024-12-20 14:44:42,140] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 111485) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
FlagEmbedding.finetune.reranker.encoder_only.base FAILED
------------------------------------------------------------
```

核心原因是 
```python
def __call__(self, features) -> list[BatchEncoding]:
```

在python3.8里面不支持list[BatchEncoding]用法?

**Comment by 545999961** [comment]
这里需要python 3.9及以上才支持，或者可以把源码里的list修改成List
