### ISSUE TITLE
fine-tune bge-reranker-base with TruncationStrategy error

### ISSUE THREAD

**Issue by YingchaoX** [FlagOpen/FlagEmbedding#202]
你好：

```
torchrun --nproc_per_node 8 \
-m FlagEmbedding.reranker.run \
--output_dir {path to save model} \
--model_name_or_path BAAI/bge-reranker-base \
--train_data ./toy_finetune_data.jsonl \
--learning_rate 6e-5 \
--fp16 \
--num_train_epochs 5 \
--per_device_train_batch_size 32 \
--gradient_accumulation_steps 4 \
--dataloader_drop_last True \
--train_group_size 16 \
--max_len 512 \
--weight_decay 0.01 \
--logging_steps 10 
```
使用上述方式微调`bge-reranker-large`,训练中报错如下
```
We need to remove 255 to truncate the input but the second sequence has a length 23. Please select another truncation strategy than TruncationStrategy.ONLY_SECOND, for instance 'longest_first' or 'only_first'.
We need to remove 269 to truncate the input but the second sequence has a length 37. Please select another truncation strategy than TruncationStrategy.ONLY_SECOND, for instance 'longest_first' or 'only_first'.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/envs/llm/lib/python3.11/site-packages/FlagEmbedding/reranker/run.py", line 95, in <module>
    main()
  File "/envs/llm/lib/python3.11/site-packages/FlagEmbedding/reranker/run.py", line 90, in main
    trainer.train()
  File "/envs/llm/lib/python3.11/site-packages/transformers/trainer.py", line 1591, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/transformers/trainer.py", line 1892, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/transformers/trainer.py", line 2776, in training_step
    loss = self.compute_loss(model, inputs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/FlagEmbedding/reranker/trainer.py", line 33, in compute_loss
    return model(inputs)['loss']
           ^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1156, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/torch/nn/parallel/distributed.py", line 1110, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])  # type: ignore[index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/accelerate/utils/operations.py", line 636, in forward
    return model_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/accelerate/utils/operations.py", line 624, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/FlagEmbedding/reranker/modeling.py", line 30, in forward
    ranker_out: SequenceClassifierOutput = self.hf_model(**batch, return_dict=True)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 1208, in forward
    outputs = self.roberta(
              ^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/envs/llm/lib/python3.11/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 812, in forward
    buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: The expanded size of the tensor (781) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [32, 781].  Tensor sizes: [1, 514]

```
通过`python -m FlagEmbedding.reranker.run --help`查看入参，并没有修改`TruncationStrategy`的参数，这里应该怎么调整？或者是对数据集的长度有要求？

谢谢！

**Comment by staoxiao** [comment]
你好，目前默认的truncation方式是只截断passage，问题不进行截断：https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/reranker/data.py#L40 
这应该是由于你的问题本身就已经超过了512 token 所导致的。 可以修改truncation=True。
