### ISSUE TITLE
运行BGE_M3 报错

### ISSUE THREAD

**Issue by JavaTribe** [FlagOpen/FlagEmbedding#418]
运行下面代码报错，python=Python 3.10.13

代码：
from FlagEmbedding import BGEM3FlagModel

    # 进行多进程操作的代码
model = BGEM3FlagModel('BAAI/bge-m3',  use_fp16=True) # Setting use_fp16 to True speeds up computation with a slight performance degradation

sentences_1 = ["What is BGE M3?", "Defination of BM25"]
sentences_2 = ["BGE M3 is an embedding model supporting dense retrieval, lexical matching and multi-vector interaction.",
               "BM25 is a bag-of-words retrieval function that ranks a set of documents based on the query terms appearing in each document"]

embeddings_1 = model.encode(sentences_1)['dense_vecs']
embeddings_2 = model.encode(sentences_2)['dense_vecs']
similarity = embeddings_1 @ embeddings_2.T
print(similarity)

报错内容：
Fetching 18 files: 100%|██████████| 18/18 [00:00<00:00, 6002.34it/s]
loading existing colbert_linear and sparse_linear---------
Fetching 18 files: 100%|██████████| 18/18 [00:00<00:00, 3596.66it/s]
loading existing colbert_linear and sparse_linear---------
encoding:   0%|          | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\code\learning\python\FlagEmbedding-master\test.py", line 13, in <module>
    embeddings_1 = model.encode(sentences_1)['dense_vecs']
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\code\learning\python\FlagEmbedding-master\FlagEmbedding\bge_m3.py", line 139, in encode
    for batch_data in tqdm(data_loader, desc='encoding', mininterval=10):
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\utils\data\dataloader.py", line 438, in __iter__
    return self._get_iterator()
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\utils\data\dataloader.py", line 386, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\utils\data\dataloader.py", line 1039, in __init__
    w.start()
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by Senna1960321** [comment]
I meet the same error.

**Comment by 545999961** [comment]
You can try to solve it this way:
`from multiprocessing import freeze_support
from FlagEmbedding import BGEM3FlagModel

def main():
    model = BGEM3FlagModel('BAAI/bge-m3',
                           use_fp16=True)  # Setting use_fp16 to True speeds up computation with a slight performance degradation

    sentences_1 = ["What is BGE M3?", "Defination of BM25"]
    sentences_2 = [
        "BGE M3 is an embedding model supporting dense retrieval, lexical matching and multi-vector interaction.",
        "BM25 is a bag-of-words retrieval function that ranks a set of documents based on the query terms appearing in each document"]

    embeddings_1 = model.encode(sentences_1)['dense_vecs']
    embeddings_2 = model.encode(sentences_2)['dense_vecs']
    similarity = embeddings_1 @ embeddings_2.T
    print(similarity)

if __name__ == '__main__':
    freeze_support()
    main()`

**Comment by 545999961** [comment]
You can try to solve it this way:
 ```
from multiprocessing import freeze_support
from FlagEmbedding import BGEM3FlagModel

def main():
    model = BGEM3FlagModel('BAAI/bge-m3',
                           use_fp16=True)  # Setting use_fp16 to True speeds up computation with a slight performance degradation

    sentences_1 = ["What is BGE M3?", "Defination of BM25"]
    sentences_2 = [
        "BGE M3 is an embedding model supporting dense retrieval, lexical matching and multi-vector interaction.",
        "BM25 is a bag-of-words retrieval function that ranks a set of documents based on the query terms appearing in each document"]

    embeddings_1 = model.encode(sentences_1)['dense_vecs']
    embeddings_2 = model.encode(sentences_2)['dense_vecs']
    similarity = embeddings_1 @ embeddings_2.T
    print(similarity)

if __name__ == '__main__':
    freeze_support()
    main()
```

**Comment by JavaTribe** [comment]
> You can try to solve it this way:
> 
> ```
> from multiprocessing import freeze_support
> from FlagEmbedding import BGEM3FlagModel
> 
> def main():
>    model = BGEM3FlagModel('BAAI/bge-m3',
>                           use_fp16=True)  # Setting use_fp16 to True speeds up computation with a slight performance degradation
> 
>    sentences_1 = ["What is BGE M3?", "Defination of BM25"]
>    sentences_2 = [
>        "BGE M3 is an embedding model supporting dense retrieval, lexical matching and multi-vector interaction.",
>        "BM25 is a bag-of-words retrieval function that ranks a set of documents based on the query terms appearing in each document"]
> 
>    embeddings_1 = model.encode(sentences_1)['dense_vecs']
>    embeddings_2 = model.encode(sentences_2)['dense_vecs']
>    similarity = embeddings_1 @ embeddings_2.T
>    print(similarity)
> 
> if __name__ == '__main__':
>    freeze_support()
>    main()
> ```
报新的错误


encoding:   0%|          | 0/1 [00:00<?, ?it/s]You're using a XLMRobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
encoding:   0%|          | 0/1 [00:20<?, ?it/s]
Traceback (most recent call last):
  File "C:\code\learning\python\FlagEmbedding-master\test.py", line 20, in <module>
    main()
  File "C:\code\learning\python\FlagEmbedding-master\test.py", line 13, in main
    embeddings_1 = model.encode(sentences_1)['dense_vecs']
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\code\learning\python\FlagEmbedding-master\FlagEmbedding\bge_m3.py", line 142, in encode
    output = self.model(batch_data,
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\code\learning\python\FlagEmbedding-master\FlagEmbedding\BGE_M3\modeling.py", line 350, in forward
    last_hidden_state = self.model(**text_input, return_dict=True).last_hidden_state
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\transformers\models\xlm_roberta\modeling_xlm_roberta.py", line 839, in forward
    embedding_output = self.embeddings(
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\transformers\models\xlm_roberta\modeling_xlm_roberta.py", line 133, in forward
    embeddings = self.LayerNorm(embeddings)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\nn\modules\normalization.py", line 196, in forward
    return F.layer_norm(
  File "C:\Users\foresee\.conda\envs\bge-m3\lib\site-packages\torch\nn\functional.py", line 2543, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

**Comment by 545999961** [comment]
fp16只支持在GPU上运行，但你这里是在CPU上运行的
如果想在CPU上使用的话，那么设置use_fp16=False便可以使用了

**Comment by 545999961** [comment]
在这里，代码似乎是在CPU上运行的，而fp16仅支持在GPU上运行
如果想要在CPU上使用的话，只需将use_fp16参数设置为False即可

**Comment by JavaTribe** [comment]
可以了，非常感谢
