### ISSUE TITLE
预训练问题

### ISSUE THREAD

**Issue by tmy123-tech** [FlagOpen/FlagEmbedding#486]
File "/data/FlagEmbedding/FlagEmbedding/bge_m3.py", line 6, in <module>
    import datasets
ModuleNotFoundError: No module named 'datasets'

**Comment by staoxiao** [comment]
需要按照datasets ：`pip install datasets `

**Comment by tmy123-tech** [comment]
您好，这个问题由于我这边别的环境干扰，已解决，但是出现了新的问题，在预训练和微调两个阶段，麻烦您能帮我看一下吗
（1）预训练命令：torchrun --nproc_per_node=1 -m FlagEmbedding.baai_general_embedding.retromae_pretrain.run --output_dir /data/taomengyuan/FlagEmbedding/out_models&nbsp; --model_name_or_path /data/LLM_weights/bge-large-zh --train_data /data/taomengyuan/FlagEmbedding/examples/pretrain/toy_pretrain_data.jsonl --learning_rate 2e-5 --num_train_epochs 2.0 --per_device_train_batch_size 1 --dataloader_drop_last True --max_seq_length 512 --logging_steps 10 --dataloader_num_workers 12&nbsp;
报错：



（2）微调命令：CUDA_VISIBLE_DEVICES=0,1 torchrun --standalone --nproc_per_node=2 -m FlagEmbedding.baai_general_embedding.finetune.run --output_dir /data/taomengyuan/FlagEmbedding/out_models --model_name_or_path /data/LLM_weights/bge-large-zh --train_data /data/taomengyuan/FlagEmbedding/examples/finetune/toy_finetune_data.jsonl --learning_rate 1e-5 --fp16 --num_train_epochs 5 --per_device_train_batch_size 8 --dataloader_drop_last True --normlized True --temperature 0.02 --query_max_len 64 --passage_max_len 256 --train_group_size 2 --negatives_cross_device&nbsp; --logging_steps 10 --query_instruction_for_retrieval ""
报错：



筱筠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FlagOpen/FlagEmbedding"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月23日(星期五) 下午5:35
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [FlagOpen/FlagEmbedding] 预训练问题 (Issue #486)





 
需要按照datasets ：pip install datasets

**Comment by tmy123-tech** [comment]
> 需要按照datasets ：`pip install datasets `
您好，这个问题我已经解决，但在微调和与训练过程中依然遇到一些问题
预训练报错：
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/FlagEmbedding/FlagEmbedding/baai_general_embedding/retromae_pretrain/run.py", line 128, in <module>
    main()
  File "/data/FlagEmbedding/FlagEmbedding/baai_general_embedding/retromae_pretrain/run.py", line 123, in main
    trainer.train(resume_from_checkpoint=training_args.resume_from_checkpoint)
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1653, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 852, in get_train_dataloader
    return self.accelerator.prepare(DataLoader(train_dataset, **dataloader_params))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 243, in __init__
    assert prefetch_factor > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2667) of binary: /usr/bin/python3.10


微调报错：
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/FlagEmbedding/FlagEmbedding/baai_general_embedding/finetune/run.py", line 111, in <module>
    main()
  File "/data/FlagEmbedding/FlagEmbedding/baai_general_embedding/finetune/run.py", line 102, in main
    trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1624, in train
    return inner_training_loop(
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 1653, in _inner_training_loop
    train_dataloader = self.get_train_dataloader()
  File "/usr/local/lib/python3.10/dist-packages/transformers/trainer.py", line 852, in get_train_dataloader
    return self.accelerator.prepare(DataLoader(train_dataset, **dataloader_params))
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/data/dataloader.py", line 241, in __init__
    raise ValueError('prefetch_factor option could only be specified in multiprocessing.'
ValueError: prefetch_factor option could only be specified in multiprocessing.let num_workers > 0 to enable multiprocessing.

**Comment by staoxiao** [comment]
建议更新transformers再试试：`pip install -U transformers`
