### ISSUE TITLE
ImportError: cannot import name 'DRESModel' from 'mteb'

### ISSUE THREAD

**Issue by AlphaNext** [FlagOpen/FlagEmbedding#531]
python eval_C-MTEB.py --model_name_or_path ../../bge-large-zh-v1.5 --task_type DuRetrieval

`Traceback (most recent call last):
  File "/Users/Downloads/llm-models/FlagEmbedding/C_MTEB/eval_C-MTEB.py", line 4, in <module>
    from flag_dres_model import FlagDRESModel
  File "/Users/Downloads/llm-models/FlagEmbedding/C_MTEB/flag_dres_model.py", line 5, in <module>
    from mteb import DRESModel
ImportError: cannot import name 'DRESModel' from 'mteb' (/Users/Downloads/llm-models/mteb/mteb/__init__.py)`

**Comment by staoxiao** [comment]
Currently, the evaluation script needs a lower version of mteb. You needs to downgrade the version of mteb.

**Comment by AlphaNext** [comment]
> Currently, the evaluation script needs a lower version of mteb. You needs to downgrade the version of mteb.

Could you recommend a mteb version, thansk

**Comment by WANGDAKEKE** [comment]
hi,  i downloaded the latest script but still facing this problem : ImportError: cannot import name 'DRESModel' from 'mteb'
![微信图片_20240329000142](https://github.com/FlagOpen/FlagEmbedding/assets/125724605/bce4318a-56e8-482d-a65f-34e21c6d1074)

**Comment by bringfull** [comment]
> > 目前，评估脚本需要较低版本的 mteb。您需要降级 mteb 的版本。
> 
> 你能推荐一个mteb版本吗，谢谢

实测1.1.0版本可用

**Comment by rnyak** [comment]
@staoxiao hello. I am getting the same error I just installed the latest code from FlagEmbedding repo. still getting `ImportError: cannot import name 'DRESModel' from 'mteb' ` error. what mteb version do you recommend? thanks.
