### ISSUE TITLE
使用HuggingFace Transformers时无法使用gpu

### ISSUE THREAD

**Issue by egg2** [FlagOpen/FlagEmbedding#616]
代码：
```
from django.http import HttpResponse
import torch
import json
import os
import time
from transformers import AutoModelForSequenceClassification, AutoTokenizer

location = os.environ.get('HUGGINGFACE_PATH')
print(location)
if location is None:
    location = "/Volumes/data/Users/awspaas/workspace/huggingface"
tokenizer = AutoTokenizer.from_pretrained(location + "/bge-reranker-large")
model = AutoModelForSequenceClassification.from_pretrained(location + "/bge-reranker-large")
#print(torch.cuda.device_count()) # 可用gpu数量
#print(torch.cuda.is_available()) #
#device = torch.device('cuda:0' if  torch.cuda.is_available()  else 'cpu' )
device = 'cuda'
model.to(device)
model.eval()

def reranker(request):
    question = request.POST.get('question')
    passage = request.POST.get('passage')
    start_time = time.time()
    data = {"result": "ok", "msg": ""}
    if question is None:
        data["result"] =  "error"
        data["msg"] = "无效参数"
        return HttpResponse(json.dumps(data))
    passageArray = []
    try:
        passageArray = json.loads(passage)
    except json.decoder.JSONDecodeError:
        data["result"] =  "error"
        data["msg"] = "无效参数"
        return HttpResponse(json.dumps(data))
    sentence_pairs = [[question, passage] for passage in passageArray]
    print(sentence_pairs)
    with torch.no_grad():
#        inputs = tokenizer(sentence_pairs, padding=True, truncation=True, return_tensors='pt', max_length=512)
#        scores = model(**inputs, return_dict=True).logits.view(-1, ).float()
#        print(scores)
#        data["data"] = {"scores":scores.tolist()}
 # get inputs
        inputs = tokenizer(sentence_pairs, padding=True, truncation=True, max_length=512, return_tensors="pt")
        inputs_on_device = {k: v.to(device) for k, v in inputs.items()}

        # calculate scores
        scores = model(**inputs, return_dict=True).logits.view(-1,).float()
        scores = torch.sigmoid(scores)
        print(scores)
        data["data"] = {"scores":scores.tolist()}
    end_time = time.time()
    data["data"]["costTime"] = end_time - start_time
    return HttpResponse(json.dumps(data))
```

异常信息：
```
Internal Server Error: /api/reranker
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/ai/aiweb-0.0.1/web/api/reranker.py", line 49, in reranker
    scores = model(**inputs, return_dict=True).logits.view(-1,).float()
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 1208, in forward
    outputs = self.roberta(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 830, in forward
    embedding_output = self.embeddings(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 126, in forward
    inputs_embeds = self.word_embeddings(input_ids)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/sparse.py", line 162, in forward
    return F.embedding(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/functional.py", line 2233, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)
```

**Comment by staoxiao** [comment]
The code should be `scores = model(** inputs_on_device, return_dict=True).logits.view(-1,).float()` rather than `scores = model(**inputs, return_dict=True).logits.view(-1,).float()`

**Comment by egg2** [comment]
Get it.It's works.Thank you
