### ISSUE TITLE
Visualized_m3加载错误，Model config for EVA02-CLIP-L-14 not found.

### ISSUE THREAD

**Issue by huangtingwei9988** [FlagOpen/FlagEmbedding#628]
@JUNJIE99 你好！感谢你们的开源工作！！
我在加载Visualized_m3时，出现了如下的报错：

`ERROR:root:Model config for EVA02-CLIP-L-14 not found; available models [].
Traceback (most recent call last):
  File "/ossfs/workspace/main.py", line 8, in <module>
    model = Visualized_BGE(model_name_bge = "/home/admin/bge-m3", model_weight="/home/admin/Visualized_m3.pth")
  File "/opt/conda/lib/python3.8/site-packages/FlagEmbedding/visual/modeling.py", line 57, in __init__
    self.model_visual, self.preprocess_train, self.preprocess_val= create_eva_vision_and_transforms(
  File "/opt/conda/lib/python3.8/site-packages/FlagEmbedding/visual/eva_clip/factory.py", line 435, in create_eva_vision_and_transforms
    model = create_model(
  File "/opt/conda/lib/python3.8/site-packages/FlagEmbedding/visual/eva_clip/factory.py", line 249, in create_model
    raise RuntimeError(f'Model config for {model_name} not found.')
RuntimeError: Model config for EVA02-CLIP-L-14 not found.`

请问EVA02-CLIP-L-14是另外的模型吗？我需要到哪里下载？我是在没连接网络的容器里面加载的。

**Comment by JUNJIE99** [comment]
您好，感谢您的关注！

你不需要额外下载这个模型，我们在`./visual/eva_clip/model_configs`里已经放置了EVA02-CLIP-L-14的config文件，正常运行的情况下，`factory.py`会自动加载该配置文件的。

建议您在仓库的`FlagEmbedding/visual`目录下再次尝试运行我们提供的样例代码。如果还有更多问题，欢迎继续讨论
