### ISSUE TITLE
Finetune llm-based layerwise reranker (openbmb/MiniCPM-2B-dpo-bf16) results in error

### ISSUE THREAD

**Issue by sungkim11** [FlagOpen/FlagEmbedding#636]
Environment: Google Colab A100

I am stuck. I need help.

1. I have installed the following due to all the errors I have encountered:

pip install -U FlagEmbedding
pip install peft
pip install deepspeed
pip install flash_attn

2. Navigated to FlagEmbedding/FlagEmbedding/llm_reranker/finetune_for_layerwise/

3. Ran this script:

torchrun --nproc_per_node 1 \
-m FlagEmbedding.llm_reranker.finetune_for_layerwise.run \
--output_dir /content \
--model_name_or_path openbmb/MiniCPM-2B-dpo-bf16 \
--train_data ../toy_finetune_data.jsonl \
--learning_rate 2e-4 \
--num_train_epochs 1 \
--per_device_train_batch_size 1 \
--gradient_accumulation_steps 16 \
--dataloader_drop_last True \
--query_max_len 512 \
--passage_max_len 512 \
--train_group_size 16 \
--logging_steps 1 \
--save_steps 2000 \
--save_total_limit 50 \
--ddp_find_unused_parameters False \
--gradient_checkpointing \
--deepspeed ../stage1.json \
--warmup_ratio 0.1 \
--bf16 \
--use_lora True \
--lora_rank 32 \
--lora_alpha 64 \
--use_flash_attn True \
--target_modules q_proj k_proj v_proj o_proj \
--start_layer 8 \
--head_multi True \
--head_type simple \
--lora_extra_parameters linear_head

and I get errors

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/FlagEmbedding/llm_reranker/finetune_for_layerwise/run.py", line 132, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/FlagEmbedding/llm_reranker/finetune_for_layerwise/run.py", line 78, in main
    base_model = get_model(model_args, training_args, tokenizer('Yes', add_special_tokens=False)['input_ids'][-1])
  File "/usr/local/lib/python3.10/dist-packages/FlagEmbedding/llm_reranker/finetune_for_layerwise/load_model.py", line 85, in get_model
    model = get_peft_model(model, peft_config)
  File "/usr/local/lib/python3.10/dist-packages/peft/mapping.py", line 136, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 1094, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 129, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py", line 136, in __init__
    super().__init__(model, config, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py", line 148, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py", line 308, in inject_adapter
    parent, target, target_name = _get_submodules(model, key)
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/other.py", line 290, in _get_submodules
    parent = model.get_submodule(".".join(key.split(".")[:-1]))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 681, in get_submodule
    raise AttributeError(mod._get_name() + " has no "
AttributeError: ModulesToSaveWrapper has no attribute `layers`
[2024-03-29 09:58:23,260] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 6293) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
FlagEmbedding.llm_reranker.finetune_for_layerwise.run FAILED

**Comment by pxy963** [comment]
I also meet the same problem.

**Comment by pxy963** [comment]
> I also meet the same problem.

AttributeError: ModulesToSaveWrapper has no attribute `layers`

**Comment by 545999961** [comment]
You may need to update 'peft'.

**Comment by pxy963** [comment]
> You may need to update 'peft'.

I have tried it, but still meet the problem.
torch == 2.2.1
peft == 0.10.0
transformer==4.39.2
flash-attn==2.5.6

**Comment by sungkim11** [comment]
I mean - I literally installed peft 3 days ago on a brand new env.

**Comment by zeruiz99** [comment]
> You may need to update 'peft'.

tried several released version, should not be this issue

**Comment by 545999961** [comment]
Apologies for any inconvenience caused. We encountered a minor issue with our recent data loading process in code, but it has been promptly resolved. You can now proceed to update the FlagEmbedding for fine-tuning purposes.

**Comment by sungkim11** [comment]
I am still getting errors on the same environment - Google Colab A100

AttributeError: ModulesToSaveWrapper has no attribute `layers`

error dump:

2024-04-02 18:31:06.717251: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-02 18:31:06.717297: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-02 18:31:06.719198: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-02 18:31:07.828199: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-04-02 18:31:09,855] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-04-02 18:31:10,277] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-04-02 18:31:10,277] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
04/02/2024 18:31:10 - WARNING - __main__ -   Process rank: 0, device: cuda:0, n_gpu: 1, distributed training: True, 16-bits training: False













label_smoothing_factor=0.0,
learning_rate=0.0002,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=/content/runs/Apr02_18-31-09_27238a5f7864,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=1.0,
logging_strategy=steps,
loss_type=only logits,
lr_scheduler_kwargs={},
lr_scheduler_type=linear,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=1.0,
optim=adamw_torch,
optim_args=None,
output_dir=/content,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=1,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=None,
run_name=/content,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=2000,
save_strategy=steps,
save_total_limit=50,
seed=42,
skip_memory_metrics=True,
split_batches=None,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.0,
)
04/02/2024 18:31:10 - INFO - __main__ -   Model parameters ModelArguments(model_name_or_path='openbmb/MiniCPM-2B-dpo-bf16', peft_model_path='', config_name=None, tokenizer_name=None, use_lora=True, lora_rank=32, lora_alpha=64.0, lora_dropout=0.1, target_modules=['q_proj', 'k_proj', 'v_proj', 'o_proj'], save_merged_lora_model=False, use_flash_attn=True, use_slow_tokenizer=False, low_cpu_mem_usage=False, cache_dir='tmp', from_peft=None, lora_extra_parameters='linear_head', start_layer=8, head_multi=True, head_type='simple')
04/02/2024 18:31:10 - INFO - __main__ -   Data parameters DataArguments(train_data='../toy_finetune_data.jsonl', train_group_size=16, query_max_len=512, passage_max_len=512, max_example_num_per_dataset=100000000, query_instruction_for_retrieval='A: ', passage_instruction_for_retrieval='B: ', cache_path='./data_dir', load_from_disk=False, load_disk_path=None, save_to_disk=False, save_disk_path=None, num_shards=0, save_max_shard_size='50GB', exit_after_save=False, shuffle_ratio=0.0)
tokenizer_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.13k/1.13k [00:00<00:00, 5.30MB/s]
tokenizer.model: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.99M/1.99M [00:00<00:00, 50.1MB/s]
special_tokens_map.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 414/414 [00:00<00:00, 2.17MB/s]
tokenizer.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6.20M/6.20M [00:00<00:00, 15.3MB/s]
config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.01k/1.01k [00:00<00:00, 6.92MB/s]
configuration_minicpm.py: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.77k/9.77k [00:00<00:00, 40.1MB/s]
A new version of the following files was downloaded from https://huggingface.co/openbmb/MiniCPM-2B-dpo-bf16:
- configuration_minicpm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
pytorch_model.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.45G/5.45G [00:35<00:00, 151MB/s]
The model was loaded with use_flash_attention_2=True, which is deprecated and may be removed in a future release. Please use `attn_implementation="flash_attention_2"` instead.
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
generation_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 113/113 [00:00<00:00, 515kB/s]
LoraConfig(peft_type=<PeftType.LORA: 'LORA'>, auto_mapping=None, base_model_name_or_path=None, revision=None, task_type=<TaskType.CAUSAL_LM: 'CAUSAL_LM'>, inference_mode=False, r=32, target_modules={'q_proj', 'k_proj', 'o_proj', 'v_proj'}, lora_alpha=64.0, lora_dropout=0.1, fan_in_fan_out=False, bias='none', use_rslora=False, modules_to_save='linear_head', init_lora_weights=True, layers_to_transform=None, layers_pattern=None, rank_pattern={}, alpha_pattern={}, megatron_config=None, megatron_core='megatron.core', loftq_config={}, use_dora=False, layer_replication=None)
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/FlagEmbedding/llm_reranker/finetune_for_layerwise/run.py", line 132, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/FlagEmbedding/llm_reranker/finetune_for_layerwise/run.py", line 78, in main
    base_model = get_model(model_args, training_args, tokenizer('Yes', add_special_tokens=False)['input_ids'][-1])
  File "/usr/local/lib/python3.10/dist-packages/FlagEmbedding/llm_reranker/finetune_for_layerwise/load_model.py", line 85, in get_model
    model = get_peft_model(model, peft_config)
  File "/usr/local/lib/python3.10/dist-packages/peft/mapping.py", line 136, in get_peft_model
    return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config, adapter_name=adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 1094, in __init__
    super().__init__(model, peft_config, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 129, in __init__
    self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/lora/model.py", line 136, in __init__
    super().__init__(model, config, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py", line 148, in __init__
    self.inject_adapter(self.model, adapter_name)
  File "/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py", line 308, in inject_adapter
    parent, target, target_name = _get_submodules(model, key)
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/other.py", line 290, in _get_submodules
    parent = model.get_submodule(".".join(key.split(".")[:-1]))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 681, in get_submodule
    raise AttributeError(mod._get_name() + " has no "
AttributeError: ModulesToSaveWrapper has no attribute `layers`
[2024-04-02 18:32:02,538] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1755) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
FlagEmbedding.llm_reranker.finetune_for_layerwise.run FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-04-02_18:32:02
  host      : 27238a5f7864
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1755)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
--use_lora True \
--lora_rank 32 \
--lora_alpha 64 \
--use_flash_attn True \
--target_modules q_proj k_proj v_proj o_proj \
--start_layer 8 \
--head_multi True \
--head_type simple \
--lora_extra_parameters linear_head

**Comment by 545999961** [comment]
> Apologies for any inconvenience caused. It is a minor issue with model loading process in code, but it has been promptly resolved. You can now proceed to update the FlagEmbedding for fine-tuning purposes.


Apologies for any inconvenience caused. It is a minor issue with model loading process in code, but it has been promptly resolved. You can now proceed to update the FlagEmbedding for fine-tuning purposes.

**Comment by sungkim11** [comment]
I just want to confirm - did you make any changes within an hour or so because I ran the code about 4 hours ago on a brand new environment.

**Comment by 545999961** [comment]
You can try `git clone https://github.com/FlagOpen/FlagEmbedding.git`, and then `pip install .`

**Comment by sungkim11** [comment]
Did you update the code recently (not yesterday) because I did that on new machine few hours ago.

**Comment by 545999961** [comment]
I'm sorry I didn't explain it clearly to you. The code was updated yesterday, but it requires `git clone https://github.com/FlagOpen/FlagEmbedding.git` + `pip install .`. If you used `pip install -U FlagEmbedding`, you'll need to reinstall with `git clone https://github.com/FlagOpen/FlagEmbedding.git` + `pip install .`.

**Comment by sungkim11** [comment]
I did that on a brand new machine/environment that had nothing installed and it still failed. I installed everything from scratch.

**Comment by sungkim11** [comment]
Issue has been fixed.
