### ISSUE TITLE
genna微调出来的权重adapter_model.safetensors 只有2m，几个文件加一块也就10m。这样是正常的吗？

### ISSUE THREAD

**Issue by hn529945497** [FlagOpen/FlagEmbedding#643]
genna微调出来的权重adapter_model.safetensors 只有2m，几个文件加一块也就10m。这样是正常的吗？
from FlagEmbedding import FlagLLMReranker
reranker_model = FlagLLMReranker(reranker_model,use_fp16=True)
微调好的路径，我直接还是这样推理吗？
这个脚本能微调千问或者别的llm模型吗
大佬有时间帮忙解答一下吧，感谢

_Originally posted by @hn529945497 in https://github.com/FlagOpen/FlagEmbedding/issues/620#issuecomment-2029093617_

**Comment by 545999961** [comment]
我们微调过程中保存的adapter_model.bin是 14.8 MB
这个脚本可以微调千问、mistral等模型
微调好后推理的话，对模型进行合并保存就可以加载了，合并保存的方式如下：
```
model = AutoModelForCausalLM.from_pretrained(model_name_or_path,
                                             cache_dir=cache_dir,
                                             trust_remote_code=True,
                                             torch_dtype=torch.bfloat16 if use_bf16 else torch.float32)
model = PeftModel.from_pretrained(model, lora_name_or_path)
model = model.merge_and_unload()
model.save_pretrained(reranker_model_path)

tokenizer = AutoTokenizer.from_pretrained(model_name_or_path,
                                          cache_dir=cache_dir,
                                          trust_remote_code=True)
if tokenizer.pad_token_id is None:
    if tokenizer.unk_token_id is not None:
        tokenizer.pad_token_id = tokenizer.unk_token_id
    elif tokenizer.eod_id is not None:
        tokenizer.pad_token_id = tokenizer.eod_id
        tokenizer.bos_token_id = tokenizer.im_start_id
        tokenizer.eos_token_id = tokenizer.im_end_id
if 'mistral' in model_name_or_path.lower():
    tokenizer.padding_side = 'left'
tokenizer.save_pretrained(reranker_model_path)
```

**Comment by hn529945497** [comment]
微调完之后的没有adapter_model.bin，只有adapter_model.safetensors，有的时候是2.65m有的时候是12.03m。
为什么我用这个微调之后的路径，然后用flag rerank llm这个类加载也能推理？
Peft加载之后是不是不用save_pretrained，也能直接推理。
微调完千问的好像推理会报错，也是要peft加载一下吗

**Comment by hn529945497** [comment]
还有现在脚本能支持qlora吗

**Comment by 545999961** [comment]
现在的脚本还不支持qlora
adapter_model.safetensors也应该是14.8m，如果改了lora参数的话可能会改变大小
如果在flag rerank llm代码里更改了模型加载方式的话，那么就不需要保存合并的模型了，保存合并的模型是为了方便后续的使用，不再需要更改代码即可使用

**Comment by hn529945497** [comment]
微调千问的话个人建议是base还是chat 啊

**Comment by 545999961** [comment]
可以用1.5 chat

**Comment by hn529945497** [comment]
再请教一下，训练gemma的时候，我看[LLaMA-Factory]里面只用q_proj,v_proj这两个，另外两个也要加上吗。
然后是为什么我用deepspeed2和3，最大的batchsize，lora_r是一样的，再大还是会超显存。像是没起作用一样。这个如何解决呢

**Comment by 545999961** [comment]
也可以只用q_proj,v_pro这两个，只是训练的参数少了点
如果超显存可以开flash attention，可以适当地缩小`gradient_accumulation_steps`或`query_max_len/passage_max_len`或`train_group_size`

**Comment by hn529945497** [comment]
> 我们微调过程中保存的adapter_model.bin是 14.8 MB 这个脚本可以微调千问、mistral等模型 微调好后推理的话，对模型进行合并保存就可以加载了，合并保存的方式如下：
> 
> ```
> model = AutoModelForCausalLM.from_pretrained(model_name_or_path,
>                                              cache_dir=cache_dir,
>                                              trust_remote_code=True,
>                                              torch_dtype=torch.bfloat16 if use_bf16 else torch.float32)
> model = PeftModel.from_pretrained(model, lora_name_or_path)
> model = model.merge_and_unload()
> model.save_pretrained(reranker_model_path)
> 
> tokenizer = AutoTokenizer.from_pretrained(model_name_or_path,
>                                           cache_dir=cache_dir,
>                                           trust_remote_code=True)
> if tokenizer.pad_token_id is None:
>     if tokenizer.unk_token_id is not None:
>         tokenizer.pad_token_id = tokenizer.unk_token_id
>     elif tokenizer.eod_id is not None:
>         tokenizer.pad_token_id = tokenizer.eod_id
>         tokenizer.bos_token_id = tokenizer.im_start_id
>         tokenizer.eos_token_id = tokenizer.im_end_id
> if 'mistral' in model_name_or_path.lower():
>     tokenizer.padding_side = 'left'
> tokenizer.save_pretrained(reranker_model_path)
> ```

Traceback (most recent call last):
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/peft/peft_model.py", line 540, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'PeftModelForCausalLM' object has no attribute 'compute_score'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/peft/tuners/lora/model.py", line 311, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LoraModel' object has no attribute 'compute_score'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_score.py", line 3956, in <module>
    score_rarank = run_rarank_all_classification_new(path, i)
  File "get_score.py", line 2458, in run_rarank_all_classification_new
    scores = reranker_model.compute_score(score_list)
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/peft/peft_model.py", line 542, in __getattr__
    return getattr(self.base_model, name)
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/peft/tuners/lora/model.py", line 313, in __getattr__
    return getattr(self.model, name)
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'GemmaForCausalLM' object has no attribute 'compute_score'

合并完之后不能用之前的方法，compute_score，来计算列表的相似度了，这个能解决吗？还是要变成embedding在计算余弦的方式来计算？

**Comment by 545999961** [comment]
需要用FlagLLMReranker来加载，将`BAAI/bge-reranker-v2-gemma`换为你合并后模型保存的地址

**Comment by hn529945497** [comment]
> 需要用FlagLLMReranker来加载，将`BAAI/bge-reranker-v2-gemma`换为你合并后模型保存的地址



  File "get_score.py", line 2462, in run_rarank_all_classification_new
    scores = reranker_model.compute_score(score_list)
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/FlagEmbedding/flag_reranker.py", line 271, in compute_score
    for inputs in tqdm(dataloader):
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/FlagEmbedding/flag_reranker.py", line 118, in __call__
    return self.tokenizer.pad(
  File "/root/miniconda/envs/thj_copy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3320, in pad
    raise ValueError(
ValueError: type of None unknown: <class 'NoneType'>. Should be one of a python, numpy, pytorch or tensorflow object.

合并之后，这个错误遇见过吗

**Comment by hn529945497** [comment]
这个是咋推理的时候，感觉是tokenization的时候，一句话的开始的标识符，给变成了none，这个能在词表里修改<|endoftext|>吗，或者还有什么别的解决方案

**Comment by 545999961** [comment]
This appears to be because the tokenizer does not have a pad_token. You can set `tokenizer.pad_token_id = k`, where k is a specific ID value
