### ISSUE TITLE
help！！！

### ISSUE THREAD

**Issue by khazic** [FlagOpen/FlagEmbedding#695]
torch.distributed.elastic.multiprocessing.api.SignalException: Process 792735 got signal: 1

我每次在运行的时候 随机会报错这个 不知道为什么会出现这种情况
我的命令行如下：

export CUDA_VISIBLE_DEVICES=0
nohup torchrun --nproc_per_node 1 \
-m FlagEmbedding.baai_general_embedding.finetune.run \
--output_dir /data/khazic/FlagEmbedding-master/saved \
--model_name_or_path /data/khazic/FlagEmbedding-master/bge-large-zh-v1.5 \
--train_data /data/khazic/FlagEmbedding-master/data/22.json \
--learning_rate 1e-5 \
--fp16 \
--num_train_epochs 5 \
--per_device_train_batch_size 32 \
--dataloader_drop_last True \
--normlized True \
--temperature 0.3 \
--query_max_len 64 \
--passage_max_len 256 \
--train_group_size 2 \
--negatives_cross_device \
--logging_steps 5 \
--save_steps 300000 \
--query_instruction_for_retrieval "" &

**Comment by staoxiao** [comment]
希望给出更详细的error log。另外，temperature 0.3太大，个人建议<=0.05。

**Comment by khazic** [comment]
{'loss': 1.4208, 'grad_norm': 2.910400629043579, 'learning_rate': 9.892529034494714e-06, 'epoch': 0.05}

  1%|          | 310/28845 [04:10<6:18:45,  1.26it/s]
  1%|          | 311/28845 [04:10<6:19:18,  1.25it/s]
  1%|          | 312/28845 [04:11<6:17:32,  1.26it/s]
  1%|          | 313/28845 [04:12<6:17:37,  1.26it/s]
  1%|          | 314/28845 [04:13<6:19:54,  1.25it/s]
  1%|          | 315/28845 [04:14<6:24:33,  1.24it/s]
                                                     
{'loss': 1.4483, 'grad_norm': 2.9629909992218018, 'learning_rate': 9.890795631825274e-06, 'epoch': 0.05}

  1%|          | 315/28845 [04:14<6:24:33,  1.24it/s]
  1%|          | 316/28845 [04:14<6:26:06,  1.23it/s]
  1%|          | 317/28845 [04:15<6:23:53,  1.24it/s]
  1%|          | 318/28845 [04:16<6:28:00,  1.23it/s]
  1%|          | 319/28845 [04:17<6:22:26,  1.24it/s]
  1%|          | 320/28845 [04:18<6:25:07,  1.23it/s]
                                                     
{'loss': 1.4621, 'grad_norm': 3.253269910812378, 'learning_rate': 9.889062229155834e-06, 'epoch': 0.06}

  1%|          | 320/28845 [04:18<6:25:07,  1.23it/s]
  1%|          | 321/28845 [04:19<6:25:18,  1.23it/s]
  1%|          | 322/28845 [04:19<6:21:07,  1.25it/s]
  1%|          | 323/28845 [04:20<6:20:30,  1.25it/s]
  1%|          | 324/28845 [04:21<6:17:59,  1.26it/s]
  1%|          | 325/28845 [04:22<6:17:05,  1.26it/s]
                                                     
{'loss': 1.4521, 'grad_norm': 2.848602771759033, 'learning_rate': 9.887328826486394e-06, 'epoch': 0.06}

  1%|          | 325/28845 [04:22<6:17:05,  1.26it/s]
  1%|          | 326/28845 [04:22<6:17:12,  1.26it/s]
  1%|          | 327/28845 [04:23<6:19:38,  1.25it/s]
  1%|          | 328/28845 [04:24<6:16:54,  1.26it/s]
  1%|          | 329/28845 [04:25<6:23:03,  1.24it/s]
  1%|          | 330/28845 [04:26<6:21:14,  1.25it/s]
                                                     
{'loss': 1.4611, 'grad_norm': 4.000938892364502, 'learning_rate': 9.885595423816954e-06, 'epoch': 0.06}

  1%|          | 330/28845 [04:26<6:21:14,  1.25it/s][2024-04-16 23:33:01,699] torch.distributed.elastic.agent.server.api: [WARNING] Received Signals.SIGHUP death signal, shutting down workers
[2024-04-16 23:33:01,700] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 792800 closing signal SIGHUP
Traceback (most recent call last):
  File "/home/liuchonghan/anaconda3/envs/khazic/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/liuchonghan/anaconda3/envs/khazic/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/liuchonghan/anaconda3/envs/khazic/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/liuchonghan/anaconda3/envs/khazic/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/liuchonghan/anaconda3/envs/khazic/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/liuchonghan/anaconda3/envs/khazic/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 255, in launch_agent
    result = agent.run()
  File "/home/liuchonghan/anaconda3/envs/khazic/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 124, in wrapper
    result = f(*args, **kwargs)
  File "/home/liuchonghan/anaconda3/envs/khazic/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 736, in run
    result = self._invoke_run(role)
  File "/home/liuchonghan/anaconda3/envs/khazic/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 877, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/liuchonghan/anaconda3/envs/khazic/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 792735 got signal: 1

**Comment by khazic** [comment]
这是我nohup里面的完整报错 我是80g的A100 不存在显存资源不够的 就是不知道是什么资源不够给停了 cpu 内存 都是ok的

**Comment by staoxiao** [comment]
参考https://github.com/pytorch/pytorch/issues/67538

**Comment by khazic** [comment]
那看来是nohup的问题了

**Comment by khazic** [comment]
我的query跟pos的信息 比较接近 所以我的loss一上来就特别小 这种情况我也不拉大temperature吗?

**Comment by khazic** [comment]
![image](https://github.com/FlagOpen/FlagEmbedding/assets/83893956/5175f4a4-ddf6-43d4-8f34-981b879a5c27)
我的这个loss的图 非常离谱

**Comment by khazic** [comment]
转成tmux后 一切正常了

**Comment by lblbk** [comment]
> 那看来是nohup的问题了

nohup 运行 python 程序后，不能直接关掉窗口，或者 ctrl+c 退出窗口，需要输入 exit 退出
