### ISSUE TITLE
RuntimeError: Already borrowed

### ISSUE THREAD

**Issue by KelleyYin** [FlagOpen/FlagEmbedding#703]
Refer to the following method to use the m3 model, an error will occur when this service is called in parallel.
```
from FlagEmbedding import BGEM3FlagModel
model = BGEM3FlagModel('BAAI/bge-m3',  use_fp16=True) 
```

```
Traceback (most recent call last):
File "/app/app.py", line 23, in route_batch_query
res_list = similarity_score(sentence_pairs, batch_size, max_query_length, max_passage_length, weights)
File "/app/model_server.py", line 88, in similarity_score
score = emb_model.compute_score(sentence_pairs,
File "/usr/local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/FlagEmbedding/bge_m3.py", line 230, in compute_score
queries_inputs = _tokenize(queries_batch, max_length=max_query_length).to(self.device)
File "/usr/local/lib/python3.9/site-packages/FlagEmbedding/bge_m3.py", line 196, in _tokenize
return self.tokenizer(
File "/usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2858, in __call__
encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
File "/usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2944, in _call_one
return self.batch_encode_plus(
File "/usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3135, in batch_encode_plus
return self._batch_encode_plus(
File "/usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 496, in _batch_encode_plus
self.set_truncation_and_padding(
File "/usr/local/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 451, in set_truncation_and_padding\
self._tokenizer.enable_truncation(**target)
RuntimeError: Already borrowed
```

**Comment by staoxiao** [comment]
The issue is from huggingface code. You can refer to discussions: https://github.com/UKPLab/sentence-transformers/issues/794 and https://github.com/huggingface/tokenizers/issues/537
