### ISSUE TITLE
验证集问题

### ISSUE THREAD

**Issue by Anthony-Sun-S** [FlagOpen/FlagEmbedding#710]
@staoxiao 大佬您好，我在训练bge-reranker-m3的时候偶然发现中间的checkpoint比最后训练完成保存的模型要好一些(最合适的参数配置还在探索)，但是因为设置了保存模型的数量然后没有记住是训练了多少个epoch，我就想用load_best_model_at_end试一下保存最佳模型，但是这个需要验证集，所以我想问一下reranker部分提供的训练代码有验证的部分吗？我该怎么处理验证集数据呢？谢谢您

**Comment by staoxiao** [comment]
您好，抱歉，目前的代码没有验证的部分，需要训练之后再进行测评。

**Comment by Anthony-Sun-S** [comment]
> 您好，抱歉，目前的代码没有验证的部分，需要训练之后再进行测评。

好的收到，谢谢您的回复，我还想问一个LM_Cocktail模型融合的问题，我在使用mix_models_by_layers的时候用的是示例给出的脚本
```
model = mix_models_by_layers(
    model_names_or_paths=["/fl/FlagEmbedding/model/BAAI_bge-reranker-v2-m3", "/fl/FlagEmbedding/examples/reranker/output/0417_project_util_3k"], 
    model_type='reranker', 
    weights=[0.5, 0.5],
    output_path="/fl/FlagEmbedding/model/mixed_reranker_2")
```
然后出现的警告和报错信息是
```
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:2025: UserWarning: for classifier.out_proj.bias: copying from a non-meta parameter in the checkpoint to a meta parameter in the current model, which is a no-op. (Did you mean to pass `assign=True` to assign items in the state dictionary to their corresponding key in the module instead of copying them in place?)
  warnings.warn(f'for {key}: copying from a non-meta parameter in the checkpoint to a meta '
Traceback (most recent call last):
  File "/fl/FlagEmbedding/examples/mix_model.py", line 10, in <module>
    model = mix_models_by_layers(
  File "/home/sh/.local/lib/python3.10/site-packages/LM_Cocktail/cocktail.py", line 162, in mix_models_by_layers
    device_map = {name: "cpu" for name, _ in meta_model.named_modules()}
UnboundLocalError: local variable 'meta_model' referenced before assignment
```
Merging models的进度条全走完了就出现了这个报错，请问我该怎么处理呢？

**Comment by staoxiao** [comment]
建议使用mix_models，不需要by_layers。

**Comment by Anthony-Sun-S** [comment]
> 建议使用mix_models，不需要by_layers。

好的我明白了，谢谢您
