### ISSUE TITLE
微调报错：RuntimeError: Could not infer dtype of NoneType

### ISSUE THREAD

**Issue by caimanjing** [FlagOpen/FlagEmbedding#77]
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 731, in convert_to_tensors
    tensor = as_tensor(value)
RuntimeError: Could not infer dtype of NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/cmj/code/emb/FlagEmbedding/FlagEmbedding/baai_general_embedding/finetune/run.py", line 109, in <module>
    main()
  File "/data/cmj/code/emb/FlagEmbedding/FlagEmbedding/baai_general_embedding/finetune/run.py", line 100, in main
    trainer.train()
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/transformers/trainer.py", line 1787, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/data/cmj/code/emb/FlagEmbedding/FlagEmbedding/baai_general_embedding/finetune/data.py", line 104, in __call__
    d_collated = self.tokenizer(
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2577, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2663, in _call_one
    return self.batch_encode_plus(
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2854, in batch_encode_plus
    return self._batch_encode_plus(
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 737, in _batch_encode_plus
    batch_outputs = self._batch_prepare_for_model(
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 817, in _batch_prepare_for_model
    batch_outputs = BatchEncoding(batch_outputs, tensor_type=return_tensors)
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 211, in __init__
    self.convert_to_tensors(tensor_type=tensor_type, prepend_batch_axis=prepend_batch_axis)
  File "/home/ma-user/anaconda3/envs/torch113-cu116/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 747, in convert_to_tensors
    raise ValueError(
ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).

数据按照要求的格式整理了，是 query:str,pos:[str],neg[str]

**Comment by staoxiao** [comment]
您好，这个报错很奇怪，无法从目前的信息中推断出具体原因，建议再仔细检查一下数据格式。也可提供一些更具体的信息，例如执行命令，以及数据数量和一些数据样例

**Comment by caimanjing** [comment]
> 您好，这个报错很奇怪，无法从目前的信息中推断出具体原因，建议再仔细检查一下数据格式。也可提供一些更具体的信息，例如执行命令，以及数据数量和一些数据样例
我把报错的tokenizer对应的query打印了出来，
['IVS各组件重启操作方法', 'NAS服务需要放通哪些端口', 'gRPC 公共Proto文件', '磁盘分区格式错误导致SUSE操作系统安装失败', 'EC-IoT有哪些产品形态', 'V3产品SmartIO卡FCOE模式是否支持10GE功能？', '如何让管理系统页面在长时间不操作时不退出登录', '如何验证IPS功能是否生效？', '同一VLAN能否配置多个网段？', 'S系列和E系列交换机端口隔离组和端口组有什么关系', '如何去掉登录DeviceManager界面时的隐私警告提示', 'SQL Server数据库场景下，为减小I/O时延，达到最佳性能，该如何调整相关参数？', '清除存储设备VIMS信息残留', 'E9000服务器的组成部分', '向YARN服务器提交MapReduce任务后，客户端长时间无响应。', 'CE交换机怎么配置匹配TCP状态的高级ACL']
Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).
报错是data.py文件里面的q_collated = self.tokenizer(
                query,
                padding=True,
                truncation=True,
                max_length=self.query_max_len,
                return_tensors="pt",
            )

**Comment by caimanjing** [comment]
执行命令是：torchrun --nproc_per_node 1 -m FlagEmbedding.baai_general_embedding.finetune.run --output_dir /home/ma-user/work/cmj/code/emb/FlagEmbedding/outputs/ --model_name_or_path /home/ma-user/work/cmj/models/bge-base-zh --train_data /home/ma-user/work/cmj/datasets/emb_data/train0822/train_cn_mind_HN.jsonl --learning_rate 1e-5 --num_train_epochs 5 --per_device_train_batch_size 16 --dataloader_drop_last True --normlized True --temperature 0.02 --query_max_len 32 --passage_max_len 128 --train_group_size 2 --negatives_cross_device

**Comment by staoxiao** [comment]
您好，出错的是`d_collated = self.tokenizer(`，猜测可以是有些数据的pos或者neg为空，可以打印passage来检查一下

**Comment by staoxiao** [comment]
您好，这个是我们的环境：
```
torch=2.0.1
transformers=4.30.0
tokenizers=0.13.3
sentence-transformers=2.2.2
sentencepiece=0.1.99
```
