### ISSUE TITLE
line 119, in index     co = faiss.GpuMultipleClonerOptions() AttributeError: module 'faiss' has no attribute 'GpuMultipleClonerOptions'

### ISSUE THREAD

**Issue by sevenandseven** [FlagOpen/FlagEmbedding#775]
"Hello, I encountered a Faiss library error when running the eval_msmarco.py script. How do I resolve this?"
this is error:

 warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
----------using 8*GPUs----------
Traceback (most recent call last):
  File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/ai/HDD/Teamwork/wangenzhi/FlagEmbedding-master/official/FlagEmbedding/FlagEmbedding/baai_general_embedding/finetune/eval_msmarco.py", line 248, in <module>
    main()
  File "/media/ai/HDD/Teamwork/wangenzhi/FlagEmbedding-master/official/FlagEmbedding/FlagEmbedding/baai_general_embedding/finetune/eval_msmarco.py", line 210, in main
    faiss_index = index(
  File "/media/ai/HDD/Teamwork/wangenzhi/FlagEmbedding-master/official/FlagEmbedding/FlagEmbedding/baai_general_embedding/finetune/eval_msmarco.py", line 119, in index
    co = faiss.GpuMultipleClonerOptions()
AttributeError: module 'faiss' has no attribute 'GpuMultipleClonerOptions'

i install faiss-gpu 1.8.0 and faiss-cpu 1.7.4。

**Comment by staoxiao** [comment]
Don't install both cpu and gpu versions for faiss. You can uninstall faiss-cpu and re-install faiss-gpu.
