### ISSUE TITLE
预训练报错

### ISSUE THREAD

**Issue by zzxxxl** [FlagOpen/FlagEmbedding#81]
Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.10/site-packages/datasets/builder.py", line 1949, in _prepare_split_single
    num_examples, num_bytes = writer.finalize()
  File "/environment/miniconda3/lib/python3.10/site-packages/datasets/arrow_writer.py", line 598, in finalize
    raise SchemaInferenceError("Please pass `features` or at least one example when writing data")
datasets.arrow_writer.SchemaInferenceError: Please pass `features` or at least one example when writing data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/environment/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/environment/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/environment/miniconda3/lib/python3.10/site-packages/FlagEmbedding/baai_general_embedding/finetune/run.py", line 109, in <module>
    main()
  File "/environment/miniconda3/lib/python3.10/site-packages/FlagEmbedding/baai_general_embedding/finetune/run.py", line 83, in main
    train_dataset = TrainDatasetForEmbedding(args=data_args, tokenizer=tokenizer)
  File "/environment/miniconda3/lib/python3.10/site-packages/FlagEmbedding/baai_general_embedding/finetune/data.py", line 32, in __init__
    self.dataset = datasets.load_dataset('json', data_files=args.train_data, split='train')
  File "/environment/miniconda3/lib/python3.10/site-packages/datasets/load.py", line 2136, in load_dataset
    builder_instance.download_and_prepare(
  File "/environment/miniconda3/lib/python3.10/site-packages/datasets/builder.py", line 954, in download_and_prepare
    self._download_and_prepare(
  File "/environment/miniconda3/lib/python3.10/site-packages/datasets/builder.py", line 1049, in _download_and_prepare
    self._prepare_split(split_generator, **prepare_split_kwargs)
  File "/environment/miniconda3/lib/python3.10/site-packages/datasets/builder.py", line 1813, in _prepare_split
    for job_id, done, content in self._prepare_split_single(
  File "/environment/miniconda3/lib/python3.10/site-packages/datasets/builder.py", line 1958, in _prepare_split_single
    raise DatasetGenerationError("An error occurred while generating the dataset") from e
datasets.builder.DatasetGenerationError: An error occurred while generating the dataset
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 185900) of binary: /environment/miniconda3/bin/python
Traceback (most recent call last):
  File "/environment/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/environment/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
FlagEmbedding.baai_general_embedding.finetune.run FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-01_21:46:15
  host      : featurize
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 185900)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
查询gpt说是在生成数据集时出现了问题，我直接按照预训练所给的指令进行操作但是报了如上错误

**Comment by zzxxxl** [comment]
哦哦不好意思，我说错了，是微调的代码，这里-m的参数是什么意思呀，是从哪里获得的呢，感觉是这个原因报错的

**Comment by zzxxxl** [comment]
我在生成hard neagive时也报错找不到模块

**Comment by zzxxxl** [comment]
/environment/miniconda3/bin/python: No module named FlagEmbedding.baai_general_embedding.finetune.hn_mine

**Comment by zzxxxl** [comment]
我在git clone的里面有这个文件，但是在系统环境里面没有

**Comment by zzxxxl** [comment]
啥也没改但是忽然可以跑了，感谢！

**Comment by staoxiao** [comment]
是因为pypi上不是最新版的代码，从那安装没有hn_mine这个文件，可以从git clone下的文件安装
```
git clone https://github.com/FlagOpen/FlagEmbedding.git
cd FlagEmbedding
pip install  -e .
```
我已更新了pypi上代码，也可以更新到最新版`pip install -U FlagEmbedding`

**Comment by zzxxxl** [comment]
哦哦好的

**Comment by zzxxxl** [comment]
请问生成预训练模型之后，可以怎么使用自己的模型，现在有许多文件，不知道用哪个：README.md    pytorch_model.bin  special_tokens_map.json  toy_finetune_data.jsonl  vocab.txt
config.json  runs               tokenizer_config.json    training_args.bin，把 pytorch_model.bin放到model那里会报错

**Comment by staoxiao** [comment]
参考：https://github.com/FlagOpen/FlagEmbedding/tree/master/FlagEmbedding/baai_general_embedding#3-load-your-model . 将your_model / finetuned_model_path替换为存储文件的路径，即设置的--output_dir参数

**Comment by staoxiao** [comment]
> 我按这个命令运行的时候：torchrun --nproc_per_node 1 -m FlagEmbedding.baai_general_embedding.finetune.run --output_dir . --model_name_or_path BAAI/bge-large-en --train_data toy_finetune_data.jsonl --learning_rate 1e-5 --fp16 --num_train_epochs 5 --per_device_train_batch_size 1 --dataloader_drop_last True --normlized True --temperature 0.02 --query_max_len 32 --passage_max_len 128 --train_group_size 2 --negatives_cross_device 没有修改任何代码或者json但是报错Traceback (most recent call last): File "/environment/miniconda3/lib/python3.10/site-packages/datasets/builder.py", line 1949, in _prepare_split_single num_examples, num_bytes = writer.finalize() File "/environment/miniconda3/lib/python3.10/site-packages/datasets/arrow_writer.py", line 598, in finalize raise SchemaInferenceError("Please pass `features` or at least one example when writing data") datasets.arrow_writer.SchemaInferenceError: Please pass `features` or at least one example when writing data

建议设置一个路径专门存储模型，比如`--output_dir  ./my_models/first_model/`

**Comment by zzxxxl** [comment]
好的谢谢辣，麻烦了

**Comment by zzxxxl** [comment]
请问导入的model具体是哪一个呀，生成太多模型我不太清楚导入哪一个，或者说导入的路径，我按您说的方法创建了这个路径，那个导入的model具体是什么呢，有太多json文件和bin文件生成，还有一个run文件夹，我不太清楚要用哪一个

**Comment by staoxiao** [comment]
并不是一个文件，而是文件夹，比如--output_dir  ./my_models/first_model/，那导入./my_models/first_model/就可以了

**Comment by zzxxxl** [comment]
终于可以了，太感谢了
