### ISSUE TITLE
生成负样本时报错

### ISSUE THREAD

**Issue by vincent507cpu** [FlagOpen/FlagEmbedding#825]
您好！
命令：
```
python -m FlagEmbedding.baai_general_embedding.finetune.hn_mine \
--model_name_or_path BAAI/bge-large-en-v1.5 \
--input_file /root/autodl-tmp/Data/model_finetuning/raw_query_pos.jsonl \
--output_file /root/autodl-tmp/Data/model_finetuning/finetune_data_minedHN.jsonl \
--range_for_sampling 2-10 \
--negative_number 3 \
--use_gpu_for_searching 
```
报错：
```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/lib/python3.10/site-packages/FlagEmbedding/baai_general_embedding/finetune/hn_mine.py", line 114, in <module>
    model = FlagModel(args.model_name_or_path, query_instruction_for_retrieval=args.query_instruction_for_retrieval)
  File "/root/miniconda3/lib/python3.10/site-packages/FlagEmbedding/flag_models.py", line 20, in __init__
    self.model = AutoModel.from_pretrained(model_name_or_path)
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3531, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```
非常感谢！

**Comment by staoxiao** [comment]
@vincent507cpu , this error indicates that you haven't downloaded the model successfully. You need to re-download the model from huggingface or huggingface-mirror.

**Comment by vincent507cpu** [comment]
OK, thanks, I'll try again. @staoxiao
