### ISSUE TITLE
微调命令问题！！！

### ISSUE THREAD

**Issue by lower01** [FlagOpen/FlagEmbedding#836]
这个微调命令到底怎么搞啊？已经在命令行试了无数次了，无法识别和找到torchrun命令，torch版本1.8没问题，查了很多资料，torchrun是用于分布式训练计算什么的，还要去nvidia官网安装nccl库什么的，但windows本地安装nccl又好麻烦啊，而且也不知道是不是这个问题，我不想要分布式训练可以吗，就一张卡，torchrun那堆命令根本没办法识别啊？？？？？？？？？？？

有没有大佬指点一下，怎么运行命令啊到底？？？
![image](https://github.com/FlagOpen/FlagEmbedding/assets/45301618/7900f5b2-ff5d-4ec3-a651-454960551e8e)

**Comment by staoxiao** [comment]
The version of your torch is too low. You can use `python xxx` instead of `torchrun xxx`.

**Comment by lower01** [comment]
> The version of your torch is too low. You can use `python xxx` instead of `torchrun xxx`.

谢谢您，我这里还有一些问题希望能请教您一下，错误报告如下：
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "F:\anaconda3\envs\RAG\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\anaconda3\envs\RAG\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\杰为软件\RAG\FlagEmbedding\baai_general_embedding\finetune\run.py", line 111, in <module>
    main()
  File "E:\杰为软件\RAG\FlagEmbedding\baai_general_embedding\finetune\run.py", line 22, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "F:\anaconda3\envs\RAG\lib\site-packages\transformers\hf_argparser.py", line 339, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 134, in __init__
  File "F:\anaconda3\envs\RAG\lib\site-packages\transformers\training_args.py", line 1641, in __post_init__
    and (self.device.type == "cpu" and not is_torch_greater_or_equal_than_2_3)
  File "F:\anaconda3\envs\RAG\lib\site-packages\transformers\training_args.py", line 2149, in device
    return self._setup_devices
  File "F:\anaconda3\envs\RAG\lib\site-packages\transformers\utils\generic.py", line 59, in __get__
    cached = self.fget(obj)
  File "F:\anaconda3\envs\RAG\lib\site-packages\transformers\training_args.py", line 2081, in _setup_devices
    self.distributed_state = PartialState(
  File "F:\anaconda3\envs\RAG\lib\site-packages\accelerate\state.py", line 192, in __init__
    torch.distributed.init_process_group(backend=self.backend, **kwargs)
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\distributed_c10d.py", line 583, in init_process_group
    default_pg = _new_process_group_helper(
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\distributed_c10d.py", line 708, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24584) of binary: F:\anaconda3\envs\RAG\python.exe
Traceback (most recent call last):
  File "F:\anaconda3\envs\RAG\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\anaconda3\envs\RAG\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\anaconda3\envs\RAG\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\run.py", line 719, in main
    run(args)
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\run.py", line 710, in run
    elastic_launch(
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\launcher\api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
FlagEmbedding.baai_general_embedding.finetune.run FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-30_15:07:39
  host      : MSI
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 24584)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
请问
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24584) of binary: F:\anaconda3\envs\RAG\python.exe错误的原因是什么呢？我是windows环境下的单卡gpu,，其实用不到分布式训练，希望您能解答

**Comment by lower01** [comment]
> The version of your torch is too low. You can use `python xxx` instead of `torchrun xxx`.

谢谢您，我这里还有一个问题，关于ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24584) of binary: F:\anaconda3\envs\RAG\python.exe错误是什么原因？如何解决呢？我是windows环境下的单卡GPU，其实用不到分布式训练
以上报错信息的相关内容如下：
  File "F:\anaconda3\envs\RAG\lib\site-packages\transformers\hf_argparser.py", line 339, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 134, in __init__
  File "F:\anaconda3\envs\RAG\lib\site-packages\transformers\training_args.py", line 1641, in __post_init__
    and (self.device.type == "cpu" and not is_torch_greater_or_equal_than_2_3)
  File "F:\anaconda3\envs\RAG\lib\site-packages\transformers\training_args.py", line 2149, in device
    return self._setup_devices
  File "F:\anaconda3\envs\RAG\lib\site-packages\transformers\utils\generic.py", line 59, in __get__
    cached = self.fget(obj)
  File "F:\anaconda3\envs\RAG\lib\site-packages\transformers\training_args.py", line 2081, in _setup_devices
    self.distributed_state = PartialState(
  File "F:\anaconda3\envs\RAG\lib\site-packages\accelerate\state.py", line 192, in __init__
    torch.distributed.init_process_group(backend=self.backend, **kwargs)
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\distributed_c10d.py", line 583, in init_process_group
    default_pg = _new_process_group_helper(
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\distributed_c10d.py", line 708, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24584) of binary: F:\anaconda3\envs\RAG\python.exe
Traceback (most recent call last):
  File "F:\anaconda3\envs\RAG\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "F:\anaconda3\envs\RAG\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\anaconda3\envs\RAG\Scripts\torchrun.exe\__main__.py", line 7, in <module>
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\run.py", line 719, in main
    run(args)
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\run.py", line 710, in run
    elastic_launch(
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\launcher\api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "F:\anaconda3\envs\RAG\lib\site-packages\torch\distributed\launcher\api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
FlagEmbedding.baai_general_embedding.finetune.run FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-05-30_15:07:39
  host      : MSI
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 24584)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

希望您能解答

**Comment by lower01** [comment]
> @lower01 can you show me the command you used?

好的，我的命令中的内容如下：
torchrun  
--nproc_per_node 1 
-m FlagEmbedding.baai_general_embedding.finetune.run 
--output_dir bge-large-zh-finetune 
--model_name_or_path bge-large-zh 
--train_data examples/finetune/toy_finetune_data.jsonl 
--learning_rate 1e-5 
--fp16 
--num_train_epochs 1 
--per_device_train_batch_size 1 
--dataloader_drop_last True 
--normlized True 
--temperature 0.02 
--query_max_len 64 
--passage_max_len 256 
--train_group_size 2 
--negatives_cross_device 
--logging_steps 10 
--save_steps 1000 
--query_instruction_for_retrieval ""

**Comment by lower01** [comment]
> @lower01 can you show me the command you used?

您好，我昨天给您发了命令，请问我的命令有什么问题吗？对于昨天提到的RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 24584) of binary: F:\anaconda3\envs\RAG\python.exe错误，是本机没有nccl库的原因吗？但是windows上好像不能安装nccl库，还是什么其它问题？

**Comment by staoxiao** [comment]
Is there still an error when using `python`?
```
python -m FlagEmbedding.baai_general_embedding.finetune.run
--output_dir bge-large-zh-finetune
--model_name_or_path bge-large-zh
--train_data examples/finetune/toy_finetune_data.jsonl
--learning_rate 1e-5
--fp16
--num_train_epochs 1
--per_device_train_batch_size 1
--dataloader_drop_last True
--normlized True
--temperature 0.02
--query_max_len 64
--passage_max_len 256
--train_group_size 2
--negatives_cross_device
--logging_steps 10
--save_steps 1000
--query_instruction_for_retrieval ""
```

**Comment by lower01** [comment]
> python -m FlagEmbedding.baai_general_embedding.finetune.run
> --output_dir bge-large-zh-finetune
> --model_name_or_path bge-large-zh
> --train_data examples/finetune/toy_finetune_data.jsonl
> --learning_rate 1e-5
> --fp16
> --num_train_epochs 1
> --per_device_train_batch_size 1
> --dataloader_drop_last True
> --normlized True
> --temperature 0.02
> --query_max_len 64
> --passage_max_len 256
> --train_group_size 2
> --negatives_cross_device
> --logging_steps 10
> --save_steps 1000
> --query_instruction_for_retrieval ""

换成python之后好像的确没有命令执行上的问题了，但是还存在与分布式训练相关的错误
![image](https://github.com/FlagOpen/FlagEmbedding/assets/45301618/af9ca39d-b172-4217-bf8c-184aa991c27d)

**Comment by staoxiao** [comment]
You can delete `negatives_cross_device `, which needs to initialize a distribution env.
```
python -m FlagEmbedding.baai_general_embedding.finetune.run
--output_dir bge-large-zh-finetune
--model_name_or_path bge-large-zh
--train_data examples/finetune/toy_finetune_data.jsonl
--learning_rate 1e-5
--fp16
--num_train_epochs 1
--per_device_train_batch_size 1
--dataloader_drop_last True
--normlized True
--temperature 0.02
--query_max_len 64
--passage_max_len 256
--train_group_size 2
--logging_steps 10
--save_steps 1000
--query_instruction_for_retrieval ""
```
Besides, I think the `per_device_train_batch_size` is too small, might influence the performance.

**Comment by lower01** [comment]
> You can delete `negatives_cross_device `, which needs to initialize a distribution env.
> 
> ```
> python -m FlagEmbedding.baai_general_embedding.finetune.run
> --output_dir bge-large-zh-finetune
> --model_name_or_path bge-large-zh
> --train_data examples/finetune/toy_finetune_data.jsonl
> --learning_rate 1e-5
> --fp16
> --num_train_epochs 1
> --per_device_train_batch_size 1
> --dataloader_drop_last True
> --normlized True
> --temperature 0.02
> --query_max_len 64
> --passage_max_len 256
> --train_group_size 2
> --logging_steps 10
> --save_steps 1000
> --query_instruction_for_retrieval ""
> ```
> 
> Besides, I think the `per_device_train_batch_size` is too small, might influence the performance.

好的，谢谢您
但更改之后能够显示错误，因为目前就是用的项目中的示例数据toy_finetune_data.jsonl来试验，里面只有10个数据就设置为了1，但有一个type error如下
![image](https://github.com/FlagOpen/FlagEmbedding/assets/45301618/dbe44f7d-9e7d-4fb2-b015-9323e0c814aa)
我不是能很好地定位原因

**Comment by lower01** [comment]
> You can delete `negatives_cross_device `, which needs to initialize a distribution env.
> 
> ```
> python -m FlagEmbedding.baai_general_embedding.finetune.run
> --output_dir bge-large-zh-finetune
> --model_name_or_path bge-large-zh
> --train_data examples/finetune/toy_finetune_data.jsonl
> --learning_rate 1e-5
> --fp16
> --num_train_epochs 1
> --per_device_train_batch_size 1
> --dataloader_drop_last True
> --normlized True
> --temperature 0.02
> --query_max_len 64
> --passage_max_len 256
> --train_group_size 2
> --logging_steps 10
> --save_steps 1000
> --query_instruction_for_retrieval ""
> ```
> 
> Besides, I think the `per_device_train_batch_size` is too small, might influence the performance.

好的，谢谢您，现在能够加载对应的数据，但是有一个type error如下：
![image](https://github.com/FlagOpen/FlagEmbedding/assets/45301618/fd8f6fab-f083-4061-ba33-841b0389615b)

我不能很好地定位问题

**Comment by staoxiao** [comment]
You can try to change the version of the transformers package, e.g., 4.37 `pip install transformers==4.37`

**Comment by lower01** [comment]
> You can try to change the version of the transformers package, e.g., 4.37 `pip install transformers==4.37`

我把我的transformer从4.41变为4.37，运行出现了3个报错问题：
![image](https://github.com/FlagOpen/FlagEmbedding/assets/45301618/d4ebdfee-d96a-4a7f-9bf1-aa29b18128ef)
![image](https://github.com/FlagOpen/FlagEmbedding/assets/45301618/d0c02650-9537-499f-b64a-277e33bbf4fe)
![image](https://github.com/FlagOpen/FlagEmbedding/assets/45301618/dcdfa583-b8b5-4bdf-a8c3-f1c4a62dee55)

对于第3个问题，我本地的模型权重文件应该是没有问题，因为之前试验过加载模型对一个句子进行嵌入，我查阅了一下资料，但是说法很有，没有很好地解决

**Comment by lower01** [comment]
> You can try to change the version of the transformers package, e.g., 4.37 `pip install transformers==4.37`

您好，我找到问题了，应该把transformer换成4.37.2，修改后再尝试既没有出现上面3个问题，也没有前面那个问题了
谢谢您

**Comment by lower01** [comment]
> You can try to change the version of the transformers package, e.g., 4.37 `pip install transformers==4.37`

您好，还想请问一下正常情况下需要多少显存的GPU微调bge-large-zh呢？在--per_device_train_batch_size 1的情况下我的4G显存无法支持微调
