### ISSUE TITLE
无法复现llama3的longbench评分

### ISSUE THREAD

**Issue by v-yunbin** [FlagOpen/FlagEmbedding#882]
**llama3**
```
评测命令：
torchrun--nproc_per_node 4 -m main.eval_longbench --model_name_or_path  ../../../../../model_hub/Meta-Llama-3-8B-Instruct/ --attn_impl flash_attention_2 --chat_template llama-3 --max_length 8192
评测结果：
Category_Metrics: {"EN Single-Doc QA": 11.65, "EN Multi-Doc QA": 8.79, "EN Summarization": 14.31, "EN Few-Shot Learning": 65.32, "Code Completion": 53.32}
```

**activate beacon llama3**（按照activate beacon说明文档训练了llama3模型）
```
评测命令：
--nproc_per_node 4 -m main.eval_longbench --model_name_or_path data/outputs/beacon-llama3-7b-chat-ft/checkpoint-15323 --enable_beacon --beacon_ratio_mix adapt-1024 --chat_template llama-3
评测结果：
Category_Metrics: {"EN Single-Doc QA": 26.28, "EN Multi-Doc QA": 17.01, "EN Summarization": 16.62, "EN Few-Shot Learning": 61.71, "Code Completion": 62.41}
```

自己评测的原生llama3的longbench评分和
这里的原生llama3的longbench评分相差甚远，https://huggingface.cn/namespace-Pt/Llama-3-8B-Instruct-80K-QLoRA-Merged
![image](https://github.com/FlagOpen/FlagEmbedding/assets/38179632/a11eaf56-df40-48bd-99a6-fbdc9bb8f660)

**Comment by namespace-Pt** [comment]
Hi，
1. 请检查你评测时是否使用的是最新的代码
2. 请检查你的llama-3模型的`generation_config.json`，其中`eos_token_id`是否设置为`[128001,128009]`，这个很重要，如果仅为128001，则llama-3输出不会正常停止，因此f1分数会很低
3. activation-beacon目前对于llama3的支持比较有限，因为llama3预训练时修改了attention mask，这点在[文档](https://github.com/FlagOpen/FlagEmbedding/blob/master/Long_LLM/activation_beacon/new/docs/training.md#llama-3)有说明，我们也在探索更好的训练activation-beacon-llama3的方法，但是尽管如此，按照文档的命令，训练出来的模型效果应该类似⬇️
`{"EN Single-Doc QA": 31.51, "EN Multi-Doc QA": 25.17, "EN Summarization": 27.37, "EN Few-Shot Learning": 65.87, "Code Completion": 63.56}`，还请检查`generation_config.json`以及代码、数据是否为最新的
4. 要复现[Llama-3-8B-Instruct-80K-QLoRA-Merged](https://huggingface.cn/namespace-Pt/Llama-3-8B-Instruct-80K-QLoRA-Merged)的结果，请参考[这里](https://github.com/FlagOpen/FlagEmbedding/tree/master/Long_LLM/longllm_qlora)，而非activation-beacon
5. 可以把`data/results/longbench`下llama-3以及activation-beacon-llama-3的测评结果中对应QA的数据集，比如`narrativeqa.json`粘贴几条在这里，方便检查

**Comment by v-yunbin** [comment]
非常感谢回答
1. 代码都是最新的，检查发现是generation_config.json，eos_token_id设置的问题。
以下是正确设置eos_token_id的结果。
llama3
`Category_Metrics: {"EN Single-Doc QA": 35.85, "EN Multi-Doc QA": 35.6, "EN Summarization": 17.17, "EN Few-Shot Learning": 65.74, "Code Completion": 51.67}`
activate beacon llama3
`Category_Metrics: {"EN Single-Doc QA": 39.28, "EN Multi-Doc QA": 34.22, "EN Summarization": 16.8, "EN Few-Shot Learning": 61.83, "Code Completion": 61.61}`
2. 很遗憾我无法复现[Llama-3-8B-Instruct-80K-QLoRA-Merged](https://huggingface.cn/namespace-Pt/Llama-3-8B-Instruct-80K-QLoRA-Merged)的结果，完全按照按照[longllm_qlora文档](https://github.com/FlagOpen/FlagEmbedding/tree/master/Long_LLM/longllm_qlora)准备环境：
```
conda create -n unsloth python=3.10
conda activate unsloth

conda install pytorch==2.2.2 pytorch-cuda=12.1 cudatoolkit xformers -c pytorch -c nvidia -c xformers
pip install transformers==4.39.3 deepspeed accelerate datasets==2.18.0 peft bitsandbytes
pip install flash-attn --no-build-isolation
pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

# these packages are used in evaluation
pip install rouge fuzzywuzzy jieba pandas seaborn python-Levenshtein
```
报以下错误，在网上查询许久，没有类似的错误，无法结果，希望可以得到帮助。
```
Traceback (most recent call last):
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/llmodel/zyb/FlagEmbedding/Long_LLM/longllm_qlora/main/train.py", line 112, in <module>
    main()
  File "/data/llmodel/zyb/FlagEmbedding/Long_LLM/longllm_qlora/main/train.py", line 107, in main
    trainer.train()
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "<string>", line 169, in _fast_inner_training_loop
  File "<string>", line 114, in prepare
  File "<string>", line 115, in <genexpr>
  File "/data/llmodel/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1169, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/data/llmodel/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1428, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 690, in __init__
    self._log_and_throw(
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel's input module must be on the same type of devices, but input module parameters locate in {'cuda', 'cpu'}.
Traceback (most recent call last):
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/llmodel/zyb/FlagEmbedding/Long_LLM/longllm_qlora/main/train.py", line 112, in <module>
    main()
  File "/data/llmodel/zyb/FlagEmbedding/Long_LLM/longllm_qlora/main/train.py", line 107, in main
    trainer.train()
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "<string>", line 169, in _fast_inner_training_loop
  File "<string>", line 114, in prepare
  File "<string>", line 115, in <genexpr>
  File "/data/llmodel/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1169, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/data/llmodel/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1428, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 690, in __init__
    self._log_and_throw(
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel's input module must be on the same type of devices, but input module parameters locate in {'cuda', 'cpu'}.
Traceback (most recent call last):
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/llmodel/zyb/FlagEmbedding/Long_LLM/longllm_qlora/main/train.py", line 112, in <module>
    main()
  File "/data/llmodel/zyb/FlagEmbedding/Long_LLM/longllm_qlora/main/train.py", line 107, in main
    trainer.train()
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "<string>", line 169, in _fast_inner_training_loop
  File "<string>", line 114, in prepare
  File "<string>", line 115, in <genexpr>
  File "/data/llmodel/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1169, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/data/llmodel/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1428, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 690, in __init__
    self._log_and_throw(
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel's input module must be on the same type of devices, but input module parameters locate in {'cpu', 'cuda'}.
Traceback (most recent call last):
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/llmodel/zyb/FlagEmbedding/Long_LLM/longllm_qlora/main/train.py", line 112, in <module>
    main()
  File "/data/llmodel/zyb/FlagEmbedding/Long_LLM/longllm_qlora/main/train.py", line 107, in main
    trainer.train()
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/lib/python3.10/site-packages/transformers/trainer.py", line 1885, in train
    return inner_training_loop(
  File "<string>", line 169, in _fast_inner_training_loop
  File "<string>", line 114, in prepare
  File "<string>", line 115, in <genexpr>
  File "/data/llmodel/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1169, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/data/llmodel/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 1428, in prepare_model
    model = torch.nn.parallel.DistributedDataParallel(
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 690, in __init__
    self._log_and_throw(
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1040, in _log_and_throw
    raise err_type(err_msg)
ValueError: DistributedDataParallel's input module must be on the same type of devices, but input module parameters locate in {'cpu', 'cuda'}.
[2024-06-13 08:53:53,139] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 98743 closing signal SIGTERM
[2024-06-13 08:53:53,754] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 98740) of binary: /data/llmodel/Tools/software_install/anaconda3/envs/unsloth/bin/python
Traceback (most recent call last):
  File "/data/llmodel/Tools/software_install/anaconda3/envs/unsloth/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.2.2', 'console_scripts', 'torchrun')())
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/llmodel/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
main.train FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-06-13_08:53:53
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 98741)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-06-13_08:53:53
  host      : ubuntu
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 98742)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-13_08:53:53
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 98740)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```
