### ISSUE TITLE
使用FlagEmbedding/C_MTEB/MKQA/multi_vector_rerank时会一直有importerror

### ISSUE THREAD

**Issue by zeruiz99** [FlagOpen/FlagEmbedding#895]
Traceback (most recent call last):
  File "/FlagEmbedding/C_MTEB/MKQA/multi_vector_rerank/step0-rerank_results.py", line 20, in <module>
    import datasets
  File "/data/miniconda3/envs/embedding/lib/python3.10/site-packages/datasets/__init__.py", line 17, in <module>
    from .arrow_dataset import Dataset
  File "/data/miniconda3/envs/embedding/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 63, in <module>
    from huggingface_hub import (
ImportError: cannot import name 'CommitInfo' from 'huggingface_hub'

使用时一直没法匹配，尝试更新huggingface版本/transformers/tokenizers版本都没能解决这个问题，pytorch版本：
conda install pytorch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 pytorch-cuda=11.8 -c pytorch -c nvidia

另外还想问这个脚本可以评测没有dense sparse colbert的reranker模型比如bge-reranker-large吗

**Comment by staoxiao** [comment]
You can try to update the package `huggingface_hub`.
If you want to run the bge-reranker model, you need to change the model class in https://github.com/FlagOpen/FlagEmbedding/blob/master/C_MTEB/MKQA/multi_vector_rerank/step0-rerank_results.py#L124
