### ISSUE TITLE
bge-reranker-v2-m3长度问题

### ISSUE THREAD

**Issue by danerlt** [FlagOpen/FlagEmbedding#920]
我使用`bge-reranker-v2-m3`重排的时候，重排的文本长度超过了8196，之后报错：`RuntimeError: The expanded size of the tensor (8196) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [2, 8196].  Tensor sizes: [1, 514]`

异常堆栈为：
```text
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/main.py", line 31, in rerank
    scores = rerank_model.rerank(query, documents)
  File "/app/rerank_model_bge.py", line 53, in rerank
    scores = self.model.compute_score(query_docs, max_length=self.max_length, normalize=True)
  File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/FlagEmbedding/flag_reranker.py", line 215, in compute_score
    scores = self.model(**inputs, return_dict=True).logits.view(-1, ).float()
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/usr/local/lib/python3.10/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 1205, in forward
    outputs = self.roberta(
  File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/transformers/models/xlm_roberta/modeling_xlm_roberta.py", line 800, in forward
    buffered_token_type_ids_expanded = buffered_token_type_ids.expand(batch_size, seq_length)
RuntimeError: The expanded size of the tensor (8196) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [2, 8196].  Tensor sizes: [1, 514]

```

我按照官方的代码封装了一下，MAX_LENGTH设置的`8196`：
```python
class RerankModelBge(object):
    def __init__(self,
                 models_path: str = MODELS_PATH,
                 model_name: str = DEFAULT_MODEL_NAME,
                 max_length: int = MAX_LENGTH):
        """初始化RerankModel

        Args:
            models_path (str): models目录路径
            model_name (str): 模型名称,也就是models目录下的子目录名称
            max_length (int): 模型max_length
        """
        logger.info(f"使用模型:{model_name}, {max_length=}")
        self.model_name = model_name

        p_models_path = Path(models_path)
        if not p_models_path.exists():
            raise ModelException(f"{models_path}目录不存在")
        p_model_path = p_models_path.joinpath(model_name)
        if not p_model_path.exists():
            raise ModelException(f"模型: {model_name} 目录不存在,请检查")
        self.model_path = str(p_model_path)

        self.max_length = max_length

        logger.info(f"模型 {self.model_name} 路径：{self.model_path}")
        logger.info(f"开始加载模型.......")
        self.model = FlagReranker(self.model_path, use_fp16=True)
        logger.info("模型加载成功")

    def rerank(self, query, documents):
        query_docs = [(query, doc) for doc in documents]
        scores = self.model.compute_score(query_docs, max_length=self.max_length, normalize=True)
        return scores


rerank_model = RerankModelBge()
```

我看源码里面是有这个max_length和截断的，为啥没有生效呢：
![image](https://github.com/FlagOpen/FlagEmbedding/assets/14197717/162e4c20-0e04-4640-8b0f-78b5d5b86981)

**Comment by staoxiao** [comment]
bge-reranker-v2-m3最大长度8192，可以确认一下是否加载对模型

**Comment by Zhouziyi828** [comment]
你的测试用例第一个超过了8192？我测的不会出现错误呀。如果超出了长度，应该会出现警告，但是不会直接报错的呀？

**Comment by danerlt** [comment]
@Zhouziyi828 内容太长了没上传上来，我实际测试的时候是使用的一个长度非常长的用例。我理解的是超过了max-length会自动的截断，但是实测并没有截断。我目前的处理是在调用模型直接直接手动的截断了。
