### ISSUE TITLE
AttributeError: module 'torch.utils._pytree' has no attribute 'register_pytree_node'

### ISSUE THREAD

**Issue by laozhai507** [FlagOpen/FlagEmbedding#960]
```
root@autodl-container-47bb4a8b0c-047da1e4:~# python -m FlagEmbedding.baai_general_embedding.finetune.hn_mine \
>     --model_name_or_path /root/autodl-tmp/models/bge-base-en-v1.5 \
>     --input_file /root/bge_ft_train_wo_titles_wo_tables-2024-07-12.jsonl \
>     --output_file /root/bge_ft_train_wo_titles_wo_tables-2024-07-12_mineHN.jsonl \
>     --range_for_sampling 2-50 \
>     --negative_number 3 \
>     --use_gpu_for_searching
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/root/miniconda3/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/root/miniconda3/lib/python3.8/site-packages/FlagEmbedding/__init__.py", line 1, in <module>
    from .flag_models import FlagModel, LLMEmbedder
  File "/root/miniconda3/lib/python3.8/site-packages/FlagEmbedding/flag_models.py", line 6, in <module>
    from transformers import AutoModel, AutoTokenizer, AutoModelForSequenceClassification, is_torch_npu_available
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/utils/__init__.py", line 34, in <module>
    from .generic import (
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/utils/generic.py", line 475, in <module>
    _torch_pytree.register_pytree_node(
AttributeError: module 'torch.utils._pytree' has no attribute 'register_pytree_node'
```
- PyTorch 2.3.1
- CUDA 12.1

**Comment by starevelyn** [comment]
same question  
2.1.0+cu118
